"""
    Radix Core API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import re  # noqa: F401
import sys  # noqa: F401

from core_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from core_client.exceptions import ApiAttributeError


def lazy_import():
    from core_client.model.fee_table import FeeTable
    from core_client.model.resource_amount import ResourceAmount
    from core_client.model.token_resource_identifier import TokenResourceIdentifier
    globals()['FeeTable'] = FeeTable
    globals()['ResourceAmount'] = ResourceAmount
    globals()['TokenResourceIdentifier'] = TokenResourceIdentifier


class EngineConfiguration(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'native_token': (TokenResourceIdentifier,),  # noqa: E501
            'maximum_message_length': (int,),  # noqa: E501
            'maximum_validators': (int,),  # noqa: E501
            'token_symbol_pattern': (str,),  # noqa: E501
            'unstaking_delay_epoch_length': (int,),  # noqa: E501
            'minimum_completed_proposals_percentage': (int,),  # noqa: E501
            'maximum_transaction_size': (int,),  # noqa: E501
            'maximum_transactions_per_round': (int,),  # noqa: E501
            'validator_fee_increase_debouncer_epoch_length': (int,),  # noqa: E501
            'maximum_rounds_per_epoch': (int,),  # noqa: E501
            'maximum_validator_fee_increase': (int,),  # noqa: E501
            'minimum_stake': (ResourceAmount,),  # noqa: E501
            'rewards_per_proposal': (ResourceAmount,),  # noqa: E501
            'reserved_symbols': ([str],),  # noqa: E501
            'fee_table': (FeeTable,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'native_token': 'native_token',  # noqa: E501
        'maximum_message_length': 'maximum_message_length',  # noqa: E501
        'maximum_validators': 'maximum_validators',  # noqa: E501
        'token_symbol_pattern': 'token_symbol_pattern',  # noqa: E501
        'unstaking_delay_epoch_length': 'unstaking_delay_epoch_length',  # noqa: E501
        'minimum_completed_proposals_percentage': 'minimum_completed_proposals_percentage',  # noqa: E501
        'maximum_transaction_size': 'maximum_transaction_size',  # noqa: E501
        'maximum_transactions_per_round': 'maximum_transactions_per_round',  # noqa: E501
        'validator_fee_increase_debouncer_epoch_length': 'validator_fee_increase_debouncer_epoch_length',  # noqa: E501
        'maximum_rounds_per_epoch': 'maximum_rounds_per_epoch',  # noqa: E501
        'maximum_validator_fee_increase': 'maximum_validator_fee_increase',  # noqa: E501
        'minimum_stake': 'minimum_stake',  # noqa: E501
        'rewards_per_proposal': 'rewards_per_proposal',  # noqa: E501
        'reserved_symbols': 'reserved_symbols',  # noqa: E501
        'fee_table': 'fee_table',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, native_token, maximum_message_length, maximum_validators, token_symbol_pattern, unstaking_delay_epoch_length, minimum_completed_proposals_percentage, maximum_transaction_size, maximum_transactions_per_round, validator_fee_increase_debouncer_epoch_length, maximum_rounds_per_epoch, maximum_validator_fee_increase, minimum_stake, rewards_per_proposal, reserved_symbols, fee_table, *args, **kwargs):  # noqa: E501
        """EngineConfiguration - a model defined in OpenAPI

        Args:
            native_token (TokenResourceIdentifier):
            maximum_message_length (int):
            maximum_validators (int):
            token_symbol_pattern (str):
            unstaking_delay_epoch_length (int):
            minimum_completed_proposals_percentage (int):
            maximum_transaction_size (int):
            maximum_transactions_per_round (int):
            validator_fee_increase_debouncer_epoch_length (int):
            maximum_rounds_per_epoch (int):
            maximum_validator_fee_increase (int):
            minimum_stake (ResourceAmount):
            rewards_per_proposal (ResourceAmount):
            reserved_symbols ([str]):
            fee_table (FeeTable):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.native_token = native_token
        self.maximum_message_length = maximum_message_length
        self.maximum_validators = maximum_validators
        self.token_symbol_pattern = token_symbol_pattern
        self.unstaking_delay_epoch_length = unstaking_delay_epoch_length
        self.minimum_completed_proposals_percentage = minimum_completed_proposals_percentage
        self.maximum_transaction_size = maximum_transaction_size
        self.maximum_transactions_per_round = maximum_transactions_per_round
        self.validator_fee_increase_debouncer_epoch_length = validator_fee_increase_debouncer_epoch_length
        self.maximum_rounds_per_epoch = maximum_rounds_per_epoch
        self.maximum_validator_fee_increase = maximum_validator_fee_increase
        self.minimum_stake = minimum_stake
        self.rewards_per_proposal = rewards_per_proposal
        self.reserved_symbols = reserved_symbols
        self.fee_table = fee_table
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, native_token, maximum_message_length, maximum_validators, token_symbol_pattern, unstaking_delay_epoch_length, minimum_completed_proposals_percentage, maximum_transaction_size, maximum_transactions_per_round, validator_fee_increase_debouncer_epoch_length, maximum_rounds_per_epoch, maximum_validator_fee_increase, minimum_stake, rewards_per_proposal, reserved_symbols, fee_table, *args, **kwargs):  # noqa: E501
        """EngineConfiguration - a model defined in OpenAPI

        Args:
            native_token (TokenResourceIdentifier):
            maximum_message_length (int):
            maximum_validators (int):
            token_symbol_pattern (str):
            unstaking_delay_epoch_length (int):
            minimum_completed_proposals_percentage (int):
            maximum_transaction_size (int):
            maximum_transactions_per_round (int):
            validator_fee_increase_debouncer_epoch_length (int):
            maximum_rounds_per_epoch (int):
            maximum_validator_fee_increase (int):
            minimum_stake (ResourceAmount):
            rewards_per_proposal (ResourceAmount):
            reserved_symbols ([str]):
            fee_table (FeeTable):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.native_token = native_token
        self.maximum_message_length = maximum_message_length
        self.maximum_validators = maximum_validators
        self.token_symbol_pattern = token_symbol_pattern
        self.unstaking_delay_epoch_length = unstaking_delay_epoch_length
        self.minimum_completed_proposals_percentage = minimum_completed_proposals_percentage
        self.maximum_transaction_size = maximum_transaction_size
        self.maximum_transactions_per_round = maximum_transactions_per_round
        self.validator_fee_increase_debouncer_epoch_length = validator_fee_increase_debouncer_epoch_length
        self.maximum_rounds_per_epoch = maximum_rounds_per_epoch
        self.maximum_validator_fee_increase = maximum_validator_fee_increase
        self.minimum_stake = minimum_stake
        self.rewards_per_proposal = rewards_per_proposal
        self.reserved_symbols = reserved_symbols
        self.fee_table = fee_table
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
