"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.intent_hash import IntentHash
globals()['IntentHash'] = IntentHash
from core_client.model.lts_transaction_status_request import LtsTransactionStatusRequest


class TestLtsTransactionStatusRequest(unittest.TestCase):
    """LtsTransactionStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionStatusRequest(self):
        """Test LtsTransactionStatusRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionStatusRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
