"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.type_info_details import TypeInfoDetails
globals()['TypeInfoDetails'] = TypeInfoDetails
from core_client.model.type_info_module_field_type_info_value import TypeInfoModuleFieldTypeInfoValue


class TestTypeInfoModuleFieldTypeInfoValue(unittest.TestCase):
    """TypeInfoModuleFieldTypeInfoValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeInfoModuleFieldTypeInfoValue(self):
        """Test TypeInfoModuleFieldTypeInfoValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypeInfoModuleFieldTypeInfoValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
