"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.active_validator import ActiveValidator
globals()['ActiveValidator'] = ActiveValidator
from core_client.model.consensus_manager_registered_validators_by_stake_index_entry_value import ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue


class TestConsensusManagerRegisteredValidatorsByStakeIndexEntryValue(unittest.TestCase):
    """ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerRegisteredValidatorsByStakeIndexEntryValue(self):
        """Test ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
