"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.stream_transactions_error_details import StreamTransactionsErrorDetails
globals()['StreamTransactionsErrorDetails'] = StreamTransactionsErrorDetails
from core_client.model.stream_transactions_error_response_all_of import StreamTransactionsErrorResponseAllOf


class TestStreamTransactionsErrorResponseAllOf(unittest.TestCase):
    """StreamTransactionsErrorResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamTransactionsErrorResponseAllOf(self):
        """Test StreamTransactionsErrorResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreamTransactionsErrorResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
