"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
globals()['EntityReference'] = EntityReference
from core_client.model.one_resource_pool_field_state_value import OneResourcePoolFieldStateValue


class TestOneResourcePoolFieldStateValue(unittest.TestCase):
    """OneResourcePoolFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneResourcePoolFieldStateValue(self):
        """Test OneResourcePoolFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OneResourcePoolFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
