"""
    Radix System API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import system_client
from system_client.model.executed_fork import ExecutedFork


class TestExecutedFork(unittest.TestCase):
    """ExecutedFork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExecutedFork(self):
        """Test ExecutedFork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExecutedFork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
