"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.error_response_type import ErrorResponseType


class TestErrorResponseType(unittest.TestCase):
    """ErrorResponseType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponseType(self):
        """Test ErrorResponseType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorResponseType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
