"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_schema_blueprint_type_reference import BlueprintSchemaBlueprintTypeReference
from core_client.model.blueprint_type_reference import BlueprintTypeReference
from core_client.model.blueprint_type_reference_kind import BlueprintTypeReferenceKind
from core_client.model.instance_schema_blueprint_type_reference import InstanceSchemaBlueprintTypeReference
from core_client.model.instance_schema_blueprint_type_reference_all_of import InstanceSchemaBlueprintTypeReferenceAllOf
globals()['BlueprintSchemaBlueprintTypeReference'] = BlueprintSchemaBlueprintTypeReference
globals()['BlueprintTypeReference'] = BlueprintTypeReference
globals()['BlueprintTypeReferenceKind'] = BlueprintTypeReferenceKind
globals()['InstanceSchemaBlueprintTypeReference'] = InstanceSchemaBlueprintTypeReference
globals()['InstanceSchemaBlueprintTypeReferenceAllOf'] = InstanceSchemaBlueprintTypeReferenceAllOf
from core_client.model.instance_schema_blueprint_type_reference import InstanceSchemaBlueprintTypeReference


class TestInstanceSchemaBlueprintTypeReference(unittest.TestCase):
    """InstanceSchemaBlueprintTypeReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceSchemaBlueprintTypeReference(self):
        """Test InstanceSchemaBlueprintTypeReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceSchemaBlueprintTypeReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
