"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.parsed_ledger_transaction import ParsedLedgerTransaction
from core_client.model.parsed_notarized_transaction import ParsedNotarizedTransaction
from core_client.model.parsed_signed_transaction_intent import ParsedSignedTransactionIntent
from core_client.model.parsed_transaction import ParsedTransaction
from core_client.model.parsed_transaction_intent import ParsedTransactionIntent
from core_client.model.parsed_transaction_intent_all_of import ParsedTransactionIntentAllOf
from core_client.model.parsed_transaction_intent_identifiers import ParsedTransactionIntentIdentifiers
from core_client.model.parsed_transaction_type import ParsedTransactionType
from core_client.model.transaction_intent import TransactionIntent
globals()['ParsedLedgerTransaction'] = ParsedLedgerTransaction
globals()['ParsedNotarizedTransaction'] = ParsedNotarizedTransaction
globals()['ParsedSignedTransactionIntent'] = ParsedSignedTransactionIntent
globals()['ParsedTransaction'] = ParsedTransaction
globals()['ParsedTransactionIntent'] = ParsedTransactionIntent
globals()['ParsedTransactionIntentAllOf'] = ParsedTransactionIntentAllOf
globals()['ParsedTransactionIntentIdentifiers'] = ParsedTransactionIntentIdentifiers
globals()['ParsedTransactionType'] = ParsedTransactionType
globals()['TransactionIntent'] = TransactionIntent
from core_client.model.parsed_transaction_intent import ParsedTransactionIntent


class TestParsedTransactionIntent(unittest.TestCase):
    """ParsedTransactionIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedTransactionIntent(self):
        """Test ParsedTransactionIntent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedTransactionIntent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
