"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_collection_schema import BlueprintCollectionSchema
from core_client.model.blueprint_collection_schema_type import BlueprintCollectionSchemaType
from core_client.model.index_blueprint_collection_schema import IndexBlueprintCollectionSchema
from core_client.model.key_value_blueprint_collection_schema import KeyValueBlueprintCollectionSchema
from core_client.model.sorted_index_blueprint_collection_schema import SortedIndexBlueprintCollectionSchema
globals()['BlueprintCollectionSchema'] = BlueprintCollectionSchema
globals()['BlueprintCollectionSchemaType'] = BlueprintCollectionSchemaType
globals()['IndexBlueprintCollectionSchema'] = IndexBlueprintCollectionSchema
globals()['KeyValueBlueprintCollectionSchema'] = KeyValueBlueprintCollectionSchema
globals()['SortedIndexBlueprintCollectionSchema'] = SortedIndexBlueprintCollectionSchema
from core_client.model.sorted_index_blueprint_collection_schema import SortedIndexBlueprintCollectionSchema


class TestSortedIndexBlueprintCollectionSchema(unittest.TestCase):
    """SortedIndexBlueprintCollectionSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortedIndexBlueprintCollectionSchema(self):
        """Test SortedIndexBlueprintCollectionSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SortedIndexBlueprintCollectionSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
