"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_payload_def import BlueprintPayloadDef
from core_client.model.blueprint_payload_def_type import BlueprintPayloadDefType
from core_client.model.generic_blueprint_payload_def import GenericBlueprintPayloadDef
from core_client.model.scoped_type_id import ScopedTypeId
from core_client.model.static_blueprint_payload_def import StaticBlueprintPayloadDef
from core_client.model.static_blueprint_payload_def_all_of import StaticBlueprintPayloadDefAllOf
globals()['BlueprintPayloadDef'] = BlueprintPayloadDef
globals()['BlueprintPayloadDefType'] = BlueprintPayloadDefType
globals()['GenericBlueprintPayloadDef'] = GenericBlueprintPayloadDef
globals()['ScopedTypeId'] = ScopedTypeId
globals()['StaticBlueprintPayloadDef'] = StaticBlueprintPayloadDef
globals()['StaticBlueprintPayloadDefAllOf'] = StaticBlueprintPayloadDefAllOf
from core_client.model.static_blueprint_payload_def import StaticBlueprintPayloadDef


class TestStaticBlueprintPayloadDef(unittest.TestCase):
    """StaticBlueprintPayloadDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaticBlueprintPayloadDef(self):
        """Test StaticBlueprintPayloadDef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaticBlueprintPayloadDef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
