"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.field_schema import FieldSchema
globals()['FieldSchema'] = FieldSchema
from core_client.model.blueprint_schema_field_partition import BlueprintSchemaFieldPartition


class TestBlueprintSchemaFieldPartition(unittest.TestCase):
    """BlueprintSchemaFieldPartition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintSchemaFieldPartition(self):
        """Test BlueprintSchemaFieldPartition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintSchemaFieldPartition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
