"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_requirement import NonFungibleRequirement
from core_client.model.requirement import Requirement
from core_client.model.requirement_type import RequirementType
from core_client.model.resource_requirement import ResourceRequirement
from core_client.model.resource_requirement_all_of import ResourceRequirementAllOf
globals()['NonFungibleRequirement'] = NonFungibleRequirement
globals()['Requirement'] = Requirement
globals()['RequirementType'] = RequirementType
globals()['ResourceRequirement'] = ResourceRequirement
globals()['ResourceRequirementAllOf'] = ResourceRequirementAllOf
from core_client.model.resource_requirement import ResourceRequirement


class TestResourceRequirement(unittest.TestCase):
    """ResourceRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceRequirement(self):
        """Test ResourceRequirement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResourceRequirement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
