"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.active_validator import ActiveValidator
globals()['ActiveValidator'] = ActiveValidator
from core_client.model.consensus_manager_field_current_validator_set_value import ConsensusManagerFieldCurrentValidatorSetValue


class TestConsensusManagerFieldCurrentValidatorSetValue(unittest.TestCase):
    """ConsensusManagerFieldCurrentValidatorSetValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldCurrentValidatorSetValue(self):
        """Test ConsensusManagerFieldCurrentValidatorSetValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldCurrentValidatorSetValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
