"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.pool_vault import PoolVault
globals()['PoolVault'] = PoolVault
from core_client.model.two_resource_pool_field_state_value import TwoResourcePoolFieldStateValue


class TestTwoResourcePoolFieldStateValue(unittest.TestCase):
    """TwoResourcePoolFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwoResourcePoolFieldStateValue(self):
        """Test TwoResourcePoolFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwoResourcePoolFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
