"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.validator_field_state_value import ValidatorFieldStateValue
globals()['ValidatorFieldStateValue'] = ValidatorFieldStateValue
from core_client.model.validator_field_state_substate_all_of import ValidatorFieldStateSubstateAllOf


class TestValidatorFieldStateSubstateAllOf(unittest.TestCase):
    """ValidatorFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidatorFieldStateSubstateAllOf(self):
        """Test ValidatorFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidatorFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
