"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.presented_badge_type import PresentedBadgeType


class TestPresentedBadgeType(unittest.TestCase):
    """PresentedBadgeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresentedBadgeType(self):
        """Test PresentedBadgeType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PresentedBadgeType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
