"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.genesis_ledger_transaction import GenesisLedgerTransaction
from core_client.model.ledger_transaction import LedgerTransaction
from core_client.model.ledger_transaction_type import LedgerTransactionType
from core_client.model.notarized_transaction import NotarizedTransaction
from core_client.model.round_update_ledger_transaction import RoundUpdateLedgerTransaction
from core_client.model.user_ledger_transaction import UserLedgerTransaction
from core_client.model.user_ledger_transaction_all_of import UserLedgerTransactionAllOf
globals()['GenesisLedgerTransaction'] = GenesisLedgerTransaction
globals()['LedgerTransaction'] = LedgerTransaction
globals()['LedgerTransactionType'] = LedgerTransactionType
globals()['NotarizedTransaction'] = NotarizedTransaction
globals()['RoundUpdateLedgerTransaction'] = RoundUpdateLedgerTransaction
globals()['UserLedgerTransaction'] = UserLedgerTransaction
globals()['UserLedgerTransactionAllOf'] = UserLedgerTransactionAllOf
from core_client.model.user_ledger_transaction import UserLedgerTransaction


class TestUserLedgerTransaction(unittest.TestCase):
    """UserLedgerTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLedgerTransaction(self):
        """Test UserLedgerTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserLedgerTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
