"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.requested_state_version_out_of_bounds_error_details import RequestedStateVersionOutOfBoundsErrorDetails
from core_client.model.stream_transactions_error_details_type import StreamTransactionsErrorDetailsType
globals()['RequestedStateVersionOutOfBoundsErrorDetails'] = RequestedStateVersionOutOfBoundsErrorDetails
globals()['StreamTransactionsErrorDetailsType'] = StreamTransactionsErrorDetailsType
from core_client.model.stream_transactions_error_details import StreamTransactionsErrorDetails


class TestStreamTransactionsErrorDetails(unittest.TestCase):
    """StreamTransactionsErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamTransactionsErrorDetails(self):
        """Test StreamTransactionsErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreamTransactionsErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
