"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ecdsa_secp256k1_signature_with_public_key import EcdsaSecp256k1SignatureWithPublicKey
from core_client.model.eddsa_ed25519_public_key import EddsaEd25519PublicKey
from core_client.model.eddsa_ed25519_signature import EddsaEd25519Signature
from core_client.model.eddsa_ed25519_signature_with_public_key import EddsaEd25519SignatureWithPublicKey
from core_client.model.eddsa_ed25519_signature_with_public_key_all_of import EddsaEd25519SignatureWithPublicKeyAllOf
from core_client.model.public_key_type import PublicKeyType
from core_client.model.signature_with_public_key import SignatureWithPublicKey
globals()['EcdsaSecp256k1SignatureWithPublicKey'] = EcdsaSecp256k1SignatureWithPublicKey
globals()['EddsaEd25519PublicKey'] = EddsaEd25519PublicKey
globals()['EddsaEd25519Signature'] = EddsaEd25519Signature
globals()['EddsaEd25519SignatureWithPublicKey'] = EddsaEd25519SignatureWithPublicKey
globals()['EddsaEd25519SignatureWithPublicKeyAllOf'] = EddsaEd25519SignatureWithPublicKeyAllOf
globals()['PublicKeyType'] = PublicKeyType
globals()['SignatureWithPublicKey'] = SignatureWithPublicKey
from core_client.model.eddsa_ed25519_signature_with_public_key import EddsaEd25519SignatureWithPublicKey


class TestEddsaEd25519SignatureWithPublicKey(unittest.TestCase):
    """EddsaEd25519SignatureWithPublicKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEddsaEd25519SignatureWithPublicKey(self):
        """Test EddsaEd25519SignatureWithPublicKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EddsaEd25519SignatureWithPublicKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
