"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.deposit_rule import DepositRule
globals()['DepositRule'] = DepositRule
from core_client.model.account_deposit_rule_index_entry_value import AccountDepositRuleIndexEntryValue


class TestAccountDepositRuleIndexEntryValue(unittest.TestCase):
    """AccountDepositRuleIndexEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountDepositRuleIndexEntryValue(self):
        """Test AccountDepositRuleIndexEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountDepositRuleIndexEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
