"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.type_info_type import TypeInfoType


class TestTypeInfoType(unittest.TestCase):
    """TypeInfoType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeInfoType(self):
        """Test TypeInfoType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypeInfoType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
