"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.method_auth_type import MethodAuthType


class TestMethodAuthType(unittest.TestCase):
    """MethodAuthType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodAuthType(self):
        """Test MethodAuthType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MethodAuthType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
