"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instance_type_pointer import InstanceTypePointer
from core_client.model.package_type_pointer import PackageTypePointer
from core_client.model.type_pointer_type import TypePointerType
globals()['InstanceTypePointer'] = InstanceTypePointer
globals()['PackageTypePointer'] = PackageTypePointer
globals()['TypePointerType'] = TypePointerType
from core_client.model.type_pointer import TypePointer


class TestTypePointer(unittest.TestCase):
    """TypePointer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypePointer(self):
        """Test TypePointer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypePointer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
