"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
from core_client.model.object_module_id import ObjectModuleId
globals()['EntityReference'] = EntityReference
globals()['ObjectModuleId'] = ObjectModuleId
from core_client.model.method_event_emitter_identifier_all_of import MethodEventEmitterIdentifierAllOf


class TestMethodEventEmitterIdentifierAllOf(unittest.TestCase):
    """MethodEventEmitterIdentifierAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodEventEmitterIdentifierAllOf(self):
        """Test MethodEventEmitterIdentifierAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MethodEventEmitterIdentifierAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
