"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_payload_status import LtsTransactionPayloadStatus
from core_client.model.notarized_transaction_hash import NotarizedTransactionHash
globals()['LtsTransactionPayloadStatus'] = LtsTransactionPayloadStatus
globals()['NotarizedTransactionHash'] = NotarizedTransactionHash
from core_client.model.lts_transaction_payload_details import LtsTransactionPayloadDetails


class TestLtsTransactionPayloadDetails(unittest.TestCase):
    """LtsTransactionPayloadDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionPayloadDetails(self):
        """Test LtsTransactionPayloadDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionPayloadDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
