"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_type import EntityType


class TestEntityType(unittest.TestCase):
    """EntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityType(self):
        """Test EntityType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
