"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.substate_key import SubstateKey
from core_client.model.substate_type import SubstateType
globals()['SubstateKey'] = SubstateKey
globals()['SubstateType'] = SubstateType
from core_client.model.substate_id_all_of import SubstateIdAllOf


class TestSubstateIdAllOf(unittest.TestCase):
    """SubstateIdAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubstateIdAllOf(self):
        """Test SubstateIdAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubstateIdAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
