"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fungible_resource_amount import FungibleResourceAmount
from core_client.model.fungible_resource_amount_all_of import FungibleResourceAmountAllOf
from core_client.model.non_fungible_resource_amount import NonFungibleResourceAmount
from core_client.model.resource_amount import ResourceAmount
from core_client.model.resource_type import ResourceType
globals()['FungibleResourceAmount'] = FungibleResourceAmount
globals()['FungibleResourceAmountAllOf'] = FungibleResourceAmountAllOf
globals()['NonFungibleResourceAmount'] = NonFungibleResourceAmount
globals()['ResourceAmount'] = ResourceAmount
globals()['ResourceType'] = ResourceType
from core_client.model.fungible_resource_amount import FungibleResourceAmount


class TestFungibleResourceAmount(unittest.TestCase):
    """FungibleResourceAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFungibleResourceAmount(self):
        """Test FungibleResourceAmount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FungibleResourceAmount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
