"""
    Radix Core API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.upcoming_fork import UpcomingFork


class TestUpcomingFork(unittest.TestCase):
    """UpcomingFork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpcomingFork(self):
        """Test UpcomingFork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpcomingFork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
