"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ledger_transaction import LedgerTransaction
from core_client.model.parsed_ledger_transaction_identifiers import ParsedLedgerTransactionIdentifiers
globals()['LedgerTransaction'] = LedgerTransaction
globals()['ParsedLedgerTransactionIdentifiers'] = ParsedLedgerTransactionIdentifiers
from core_client.model.parsed_ledger_transaction_all_of import ParsedLedgerTransactionAllOf


class TestParsedLedgerTransactionAllOf(unittest.TestCase):
    """ParsedLedgerTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedLedgerTransactionAllOf(self):
        """Test ParsedLedgerTransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedLedgerTransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
