"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.virtual_lazy_load_schema import VirtualLazyLoadSchema


class TestVirtualLazyLoadSchema(unittest.TestCase):
    """VirtualLazyLoadSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirtualLazyLoadSchema(self):
        """Test VirtualLazyLoadSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VirtualLazyLoadSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
