"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.substate import Substate
globals()['Substate'] = Substate
from core_client.model.state_package_response import StatePackageResponse


class TestStatePackageResponse(unittest.TestCase):
    """StatePackageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatePackageResponse(self):
        """Test StatePackageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatePackageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
