"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ledger_transaction_type import LedgerTransactionType


class TestLedgerTransactionType(unittest.TestCase):
    """LedgerTransactionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLedgerTransactionType(self):
        """Test LedgerTransactionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LedgerTransactionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
