"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.encrypted_message_curve_decryptor_set import EncryptedMessageCurveDecryptorSet
globals()['EncryptedMessageCurveDecryptorSet'] = EncryptedMessageCurveDecryptorSet
from core_client.model.encrypted_transaction_message_all_of import EncryptedTransactionMessageAllOf


class TestEncryptedTransactionMessageAllOf(unittest.TestCase):
    """EncryptedTransactionMessageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncryptedTransactionMessageAllOf(self):
        """Test EncryptedTransactionMessageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EncryptedTransactionMessageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
