"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.field_schema_feature_condition import FieldSchemaFeatureCondition
from core_client.model.type_pointer import TypePointer
globals()['FieldSchemaFeatureCondition'] = FieldSchemaFeatureCondition
globals()['TypePointer'] = TypePointer
from core_client.model.field_schema import FieldSchema


class TestFieldSchema(unittest.TestCase):
    """FieldSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldSchema(self):
        """Test FieldSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
