"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.component_method_target_identifier_all_of import ComponentMethodTargetIdentifierAllOf


class TestComponentMethodTargetIdentifierAllOf(unittest.TestCase):
    """ComponentMethodTargetIdentifierAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentMethodTargetIdentifierAllOf(self):
        """Test ComponentMethodTargetIdentifierAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComponentMethodTargetIdentifierAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
