"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_payload_status import LtsTransactionPayloadStatus


class TestLtsTransactionPayloadStatus(unittest.TestCase):
    """LtsTransactionPayloadStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionPayloadStatus(self):
        """Test LtsTransactionPayloadStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionPayloadStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
