"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_tracker_field_state_value import TransactionTrackerFieldStateValue


class TestTransactionTrackerFieldStateValue(unittest.TestCase):
    """TransactionTrackerFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionTrackerFieldStateValue(self):
        """Test TransactionTrackerFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionTrackerFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
