"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.active_validator_key import ActiveValidatorKey
from core_client.model.consensus_manager_registered_validators_by_stake_index_entry_value import ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue
globals()['ActiveValidatorKey'] = ActiveValidatorKey
globals()['ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue'] = ConsensusManagerRegisteredValidatorsByStakeIndexEntryValue
from core_client.model.consensus_manager_registered_validators_by_stake_index_entry_substate_all_of import ConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf


class TestConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf(unittest.TestCase):
    """ConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf(self):
        """Test ConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
