"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.active_validator_index import ActiveValidatorIndex
globals()['ActiveValidatorIndex'] = ActiveValidatorIndex
from core_client.model.leader_proposal_history import LeaderProposalHistory


class TestLeaderProposalHistory(unittest.TestCase):
    """LeaderProposalHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeaderProposalHistory(self):
        """Test LeaderProposalHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LeaderProposalHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
