"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_format_options import SborFormatOptions


class TestSborFormatOptions(unittest.TestCase):
    """SborFormatOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSborFormatOptions(self):
        """Test SborFormatOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SborFormatOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
