"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_fungible_resource_balance import LtsFungibleResourceBalance
from core_client.model.state_version import StateVersion
globals()['LtsFungibleResourceBalance'] = LtsFungibleResourceBalance
globals()['StateVersion'] = StateVersion
from core_client.model.lts_state_account_all_fungible_resource_balances_response import LtsStateAccountAllFungibleResourceBalancesResponse


class TestLtsStateAccountAllFungibleResourceBalancesResponse(unittest.TestCase):
    """LtsStateAccountAllFungibleResourceBalancesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsStateAccountAllFungibleResourceBalancesResponse(self):
        """Test LtsStateAccountAllFungibleResourceBalancesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsStateAccountAllFungibleResourceBalancesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
