"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.all_of_proof_rule import AllOfProofRule
from core_client.model.amount_of_proof_rule import AmountOfProofRule
from core_client.model.amount_of_proof_rule_all_of import AmountOfProofRuleAllOf
from core_client.model.any_of_proof_rule import AnyOfProofRule
from core_client.model.count_of_proof_rule import CountOfProofRule
from core_client.model.proof_rule import ProofRule
from core_client.model.proof_rule_type import ProofRuleType
from core_client.model.require_proof_rule import RequireProofRule
globals()['AllOfProofRule'] = AllOfProofRule
globals()['AmountOfProofRule'] = AmountOfProofRule
globals()['AmountOfProofRuleAllOf'] = AmountOfProofRuleAllOf
globals()['AnyOfProofRule'] = AnyOfProofRule
globals()['CountOfProofRule'] = CountOfProofRule
globals()['ProofRule'] = ProofRule
globals()['ProofRuleType'] = ProofRuleType
globals()['RequireProofRule'] = RequireProofRule
from core_client.model.amount_of_proof_rule import AmountOfProofRule


class TestAmountOfProofRule(unittest.TestCase):
    """AmountOfProofRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmountOfProofRule(self):
        """Test AmountOfProofRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AmountOfProofRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
