"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.generic_substitution import GenericSubstitution
from core_client.model.generic_substitution_type import GenericSubstitutionType
from core_client.model.local_generic_substitution import LocalGenericSubstitution
from core_client.model.local_generic_substitution_all_of import LocalGenericSubstitutionAllOf
from core_client.model.remote_generic_substitution import RemoteGenericSubstitution
from core_client.model.scoped_type_id import ScopedTypeId
globals()['GenericSubstitution'] = GenericSubstitution
globals()['GenericSubstitutionType'] = GenericSubstitutionType
globals()['LocalGenericSubstitution'] = LocalGenericSubstitution
globals()['LocalGenericSubstitutionAllOf'] = LocalGenericSubstitutionAllOf
globals()['RemoteGenericSubstitution'] = RemoteGenericSubstitution
globals()['ScopedTypeId'] = ScopedTypeId
from core_client.model.local_generic_substitution import LocalGenericSubstitution


class TestLocalGenericSubstitution(unittest.TestCase):
    """LocalGenericSubstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalGenericSubstitution(self):
        """Test LocalGenericSubstitution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalGenericSubstitution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
