"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_definition import BlueprintDefinition
globals()['BlueprintDefinition'] = BlueprintDefinition
from core_client.model.package_blueprint_definition_entry_value import PackageBlueprintDefinitionEntryValue


class TestPackageBlueprintDefinitionEntryValue(unittest.TestCase):
    """PackageBlueprintDefinitionEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageBlueprintDefinitionEntryValue(self):
        """Test PackageBlueprintDefinitionEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageBlueprintDefinitionEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
