"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.string_plaintext_message_content_all_of import StringPlaintextMessageContentAllOf


class TestStringPlaintextMessageContentAllOf(unittest.TestCase):
    """StringPlaintextMessageContentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStringPlaintextMessageContentAllOf(self):
        """Test StringPlaintextMessageContentAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StringPlaintextMessageContentAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
