"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.requirement import Requirement
globals()['Requirement'] = Requirement
from core_client.model.require_proof_rule_all_of import RequireProofRuleAllOf


class TestRequireProofRuleAllOf(unittest.TestCase):
    """RequireProofRuleAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequireProofRuleAllOf(self):
        """Test RequireProofRuleAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequireProofRuleAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
