"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_presented_badge_all_of import NonFungiblePresentedBadgeAllOf


class TestNonFungiblePresentedBadgeAllOf(unittest.TestCase):
    """NonFungiblePresentedBadgeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungiblePresentedBadgeAllOf(self):
        """Test NonFungiblePresentedBadgeAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungiblePresentedBadgeAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
