"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.data_struct import DataStruct
globals()['DataStruct'] = DataStruct
from core_client.model.access_controller_field_state_value import AccessControllerFieldStateValue


class TestAccessControllerFieldStateValue(unittest.TestCase):
    """AccessControllerFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessControllerFieldStateValue(self):
        """Test AccessControllerFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessControllerFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
