"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_dependencies import BlueprintDependencies
globals()['BlueprintDependencies'] = BlueprintDependencies
from core_client.model.package_blueprint_dependencies_entry_value import PackageBlueprintDependenciesEntryValue


class TestPackageBlueprintDependenciesEntryValue(unittest.TestCase):
    """PackageBlueprintDependenciesEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageBlueprintDependenciesEntryValue(self):
        """Test PackageBlueprintDependenciesEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageBlueprintDependenciesEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
