"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.encrypted_message_decryptor import EncryptedMessageDecryptor


class TestEncryptedMessageDecryptor(unittest.TestCase):
    """EncryptedMessageDecryptor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncryptedMessageDecryptor(self):
        """Test EncryptedMessageDecryptor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EncryptedMessageDecryptor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
