"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.substate_system_structure_type import SubstateSystemStructureType


class TestSubstateSystemStructureType(unittest.TestCase):
    """SubstateSystemStructureType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubstateSystemStructureType(self):
        """Test SubstateSystemStructureType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubstateSystemStructureType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
