"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.basic_error_response import BasicErrorResponse
from core_client.model.error_response import ErrorResponse
from core_client.model.error_response_type import ErrorResponseType
from core_client.model.lts_transaction_submit_error_response import LtsTransactionSubmitErrorResponse
from core_client.model.stream_transactions_error_details import StreamTransactionsErrorDetails
from core_client.model.stream_transactions_error_response import StreamTransactionsErrorResponse
from core_client.model.stream_transactions_error_response_all_of import StreamTransactionsErrorResponseAllOf
from core_client.model.transaction_submit_error_response import TransactionSubmitErrorResponse
globals()['BasicErrorResponse'] = BasicErrorResponse
globals()['ErrorResponse'] = ErrorResponse
globals()['ErrorResponseType'] = ErrorResponseType
globals()['LtsTransactionSubmitErrorResponse'] = LtsTransactionSubmitErrorResponse
globals()['StreamTransactionsErrorDetails'] = StreamTransactionsErrorDetails
globals()['StreamTransactionsErrorResponse'] = StreamTransactionsErrorResponse
globals()['StreamTransactionsErrorResponseAllOf'] = StreamTransactionsErrorResponseAllOf
globals()['TransactionSubmitErrorResponse'] = TransactionSubmitErrorResponse
from core_client.model.stream_transactions_error_response import StreamTransactionsErrorResponse


class TestStreamTransactionsErrorResponse(unittest.TestCase):
    """StreamTransactionsErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamTransactionsErrorResponse(self):
        """Test StreamTransactionsErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreamTransactionsErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
