"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_function_target_identifier_all_of import BlueprintFunctionTargetIdentifierAllOf


class TestBlueprintFunctionTargetIdentifierAllOf(unittest.TestCase):
    """BlueprintFunctionTargetIdentifierAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintFunctionTargetIdentifierAllOf(self):
        """Test BlueprintFunctionTargetIdentifierAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintFunctionTargetIdentifierAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
