"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.state_component_descendent_node import StateComponentDescendentNode
from core_client.model.substate import Substate
from core_client.model.vault_balance import VaultBalance
globals()['StateComponentDescendentNode'] = StateComponentDescendentNode
globals()['Substate'] = Substate
globals()['VaultBalance'] = VaultBalance
from core_client.model.state_access_controller_response import StateAccessControllerResponse


class TestStateAccessControllerResponse(unittest.TestCase):
    """StateAccessControllerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateAccessControllerResponse(self):
        """Test StateAccessControllerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateAccessControllerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
