"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ecdsa_secp256k1_public_key import EcdsaSecp256k1PublicKey
from core_client.model.ecdsa_secp256k1_signature import EcdsaSecp256k1Signature
globals()['EcdsaSecp256k1PublicKey'] = EcdsaSecp256k1PublicKey
globals()['EcdsaSecp256k1Signature'] = EcdsaSecp256k1Signature
from core_client.model.timestamped_validator_signature import TimestampedValidatorSignature


class TestTimestampedValidatorSignature(unittest.TestCase):
    """TimestampedValidatorSignature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimestampedValidatorSignature(self):
        """Test TimestampedValidatorSignature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimestampedValidatorSignature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
