"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.role_details import RoleDetails


class TestRoleDetails(unittest.TestCase):
    """RoleDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleDetails(self):
        """Test RoleDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
