"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.notarized_transaction import NotarizedTransaction
from core_client.model.parsed_notarized_transaction_all_of_validation_error import ParsedNotarizedTransactionAllOfValidationError
from core_client.model.parsed_notarized_transaction_identifiers import ParsedNotarizedTransactionIdentifiers
globals()['NotarizedTransaction'] = NotarizedTransaction
globals()['ParsedNotarizedTransactionAllOfValidationError'] = ParsedNotarizedTransactionAllOfValidationError
globals()['ParsedNotarizedTransactionIdentifiers'] = ParsedNotarizedTransactionIdentifiers
from core_client.model.parsed_notarized_transaction_all_of import ParsedNotarizedTransactionAllOf


class TestParsedNotarizedTransactionAllOf(unittest.TestCase):
    """ParsedNotarizedTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedNotarizedTransactionAllOf(self):
        """Test ParsedNotarizedTransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedNotarizedTransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
