"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.data_struct import DataStruct
globals()['DataStruct'] = DataStruct
from core_client.model.non_fungible_resource_manager_data_entry_value import NonFungibleResourceManagerDataEntryValue


class TestNonFungibleResourceManagerDataEntryValue(unittest.TestCase):
    """NonFungibleResourceManagerDataEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleResourceManagerDataEntryValue(self):
        """Test NonFungibleResourceManagerDataEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleResourceManagerDataEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
