"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.field_substate_key import FieldSubstateKey
from core_client.model.map_substate_key import MapSubstateKey
from core_client.model.map_substate_key_all_of import MapSubstateKeyAllOf
from core_client.model.sorted_substate_key import SortedSubstateKey
from core_client.model.substate_key import SubstateKey
from core_client.model.substate_key_type import SubstateKeyType
globals()['FieldSubstateKey'] = FieldSubstateKey
globals()['MapSubstateKey'] = MapSubstateKey
globals()['MapSubstateKeyAllOf'] = MapSubstateKeyAllOf
globals()['SortedSubstateKey'] = SortedSubstateKey
globals()['SubstateKey'] = SubstateKey
globals()['SubstateKeyType'] = SubstateKeyType
from core_client.model.map_substate_key import MapSubstateKey


class TestMapSubstateKey(unittest.TestCase):
    """MapSubstateKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapSubstateKey(self):
        """Test MapSubstateKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MapSubstateKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
