"""
    Radix System API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import system_client
from system_client.model.peer import Peer
globals()['Peer'] = Peer
from system_client.model.system_peers_response import SystemPeersResponse


class TestSystemPeersResponse(unittest.TestCase):
    """SystemPeersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemPeersResponse(self):
        """Test SystemPeersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemPeersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
