"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_data import SborData
globals()['SborData'] = SborData
from core_client.model.local_type_id import LocalTypeId


class TestLocalTypeId(unittest.TestCase):
    """LocalTypeId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalTypeId(self):
        """Test LocalTypeId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalTypeId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
