"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_version_key import BlueprintVersionKey


class TestBlueprintVersionKey(unittest.TestCase):
    """BlueprintVersionKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintVersionKey(self):
        """Test BlueprintVersionKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintVersionKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
