"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_module import EntityModule
from core_client.model.entity_type import EntityType
from core_client.model.partition_kind import PartitionKind
from core_client.model.substate_key import SubstateKey
from core_client.model.substate_type import SubstateType
globals()['EntityModule'] = EntityModule
globals()['EntityType'] = EntityType
globals()['PartitionKind'] = PartitionKind
globals()['SubstateKey'] = SubstateKey
globals()['SubstateType'] = SubstateType
from core_client.model.substate_id import SubstateId


class TestSubstateId(unittest.TestCase):
    """SubstateId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubstateId(self):
        """Test SubstateId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubstateId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
