"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fully_scoped_type_id import FullyScopedTypeId
from core_client.model.key_value_store_entry_structure import KeyValueStoreEntryStructure
from core_client.model.key_value_store_entry_structure_all_of import KeyValueStoreEntryStructureAllOf
from core_client.model.object_field_structure import ObjectFieldStructure
from core_client.model.object_index_partition_entry_structure import ObjectIndexPartitionEntryStructure
from core_client.model.object_key_value_partition_entry_structure import ObjectKeyValuePartitionEntryStructure
from core_client.model.object_sorted_index_partition_entry_structure import ObjectSortedIndexPartitionEntryStructure
from core_client.model.substate_system_structure import SubstateSystemStructure
from core_client.model.substate_system_structure_type import SubstateSystemStructureType
from core_client.model.system_field_structure import SystemFieldStructure
from core_client.model.system_schema_structure import SystemSchemaStructure
globals()['FullyScopedTypeId'] = FullyScopedTypeId
globals()['KeyValueStoreEntryStructure'] = KeyValueStoreEntryStructure
globals()['KeyValueStoreEntryStructureAllOf'] = KeyValueStoreEntryStructureAllOf
globals()['ObjectFieldStructure'] = ObjectFieldStructure
globals()['ObjectIndexPartitionEntryStructure'] = ObjectIndexPartitionEntryStructure
globals()['ObjectKeyValuePartitionEntryStructure'] = ObjectKeyValuePartitionEntryStructure
globals()['ObjectSortedIndexPartitionEntryStructure'] = ObjectSortedIndexPartitionEntryStructure
globals()['SubstateSystemStructure'] = SubstateSystemStructure
globals()['SubstateSystemStructureType'] = SubstateSystemStructureType
globals()['SystemFieldStructure'] = SystemFieldStructure
globals()['SystemSchemaStructure'] = SystemSchemaStructure
from core_client.model.key_value_store_entry_structure import KeyValueStoreEntryStructure


class TestKeyValueStoreEntryStructure(unittest.TestCase):
    """KeyValueStoreEntryStructure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValueStoreEntryStructure(self):
        """Test KeyValueStoreEntryStructure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyValueStoreEntryStructure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
