"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.payment_to_royalty_recipient import PaymentToRoyaltyRecipient
globals()['PaymentToRoyaltyRecipient'] = PaymentToRoyaltyRecipient
from core_client.model.fee_destination import FeeDestination


class TestFeeDestination(unittest.TestCase):
    """FeeDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeDestination(self):
        """Test FeeDestination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FeeDestination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
