"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.local_type_id import LocalTypeId
from core_client.model.schema_hash import SchemaHash
globals()['LocalTypeId'] = LocalTypeId
globals()['SchemaHash'] = SchemaHash
from core_client.model.fully_scoped_type_id import FullyScopedTypeId


class TestFullyScopedTypeId(unittest.TestCase):
    """FullyScopedTypeId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullyScopedTypeId(self):
        """Test FullyScopedTypeId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullyScopedTypeId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
