"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.key_value_store_info import KeyValueStoreInfo
from core_client.model.key_value_store_type_info_details import KeyValueStoreTypeInfoDetails
from core_client.model.key_value_store_type_info_details_all_of import KeyValueStoreTypeInfoDetailsAllOf
from core_client.model.object_type_info_details import ObjectTypeInfoDetails
from core_client.model.type_info_details import TypeInfoDetails
from core_client.model.type_info_type import TypeInfoType
globals()['KeyValueStoreInfo'] = KeyValueStoreInfo
globals()['KeyValueStoreTypeInfoDetails'] = KeyValueStoreTypeInfoDetails
globals()['KeyValueStoreTypeInfoDetailsAllOf'] = KeyValueStoreTypeInfoDetailsAllOf
globals()['ObjectTypeInfoDetails'] = ObjectTypeInfoDetails
globals()['TypeInfoDetails'] = TypeInfoDetails
globals()['TypeInfoType'] = TypeInfoType
from core_client.model.key_value_store_type_info_details import KeyValueStoreTypeInfoDetails


class TestKeyValueStoreTypeInfoDetails(unittest.TestCase):
    """KeyValueStoreTypeInfoDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValueStoreTypeInfoDetails(self):
        """Test KeyValueStoreTypeInfoDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyValueStoreTypeInfoDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
