"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ecdsa_secp256k1_public_key import EcdsaSecp256k1PublicKey
globals()['EcdsaSecp256k1PublicKey'] = EcdsaSecp256k1PublicKey
from core_client.model.active_validator import ActiveValidator


class TestActiveValidator(unittest.TestCase):
    """ActiveValidator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActiveValidator(self):
        """Test ActiveValidator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActiveValidator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
