"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_data import SborData
from core_client.model.transaction_status import TransactionStatus
globals()['SborData'] = SborData
globals()['TransactionStatus'] = TransactionStatus
from core_client.model.transaction_call_preview_response import TransactionCallPreviewResponse


class TestTransactionCallPreviewResponse(unittest.TestCase):
    """TransactionCallPreviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCallPreviewResponse(self):
        """Test TransactionCallPreviewResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCallPreviewResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
