"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule_node_type import AccessRuleNodeType
from core_client.model.all_of_access_rule_node import AllOfAccessRuleNode
from core_client.model.any_of_access_rule_node import AnyOfAccessRuleNode
from core_client.model.proof_access_rule_node import ProofAccessRuleNode
globals()['AccessRuleNodeType'] = AccessRuleNodeType
globals()['AllOfAccessRuleNode'] = AllOfAccessRuleNode
globals()['AnyOfAccessRuleNode'] = AnyOfAccessRuleNode
globals()['ProofAccessRuleNode'] = ProofAccessRuleNode
from core_client.model.access_rule_node import AccessRuleNode


class TestAccessRuleNode(unittest.TestCase):
    """AccessRuleNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRuleNode(self):
        """Test AccessRuleNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRuleNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
