"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule_node import AccessRuleNode
globals()['AccessRuleNode'] = AccessRuleNode
from core_client.model.any_of_access_rule_node_all_of import AnyOfAccessRuleNodeAllOf


class TestAnyOfAccessRuleNodeAllOf(unittest.TestCase):
    """AnyOfAccessRuleNodeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfAccessRuleNodeAllOf(self):
        """Test AnyOfAccessRuleNodeAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnyOfAccessRuleNodeAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
