"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.local_non_fungible_key import LocalNonFungibleKey
from core_client.model.non_fungible_vault_contents_index_entry_value import NonFungibleVaultContentsIndexEntryValue
globals()['LocalNonFungibleKey'] = LocalNonFungibleKey
globals()['NonFungibleVaultContentsIndexEntryValue'] = NonFungibleVaultContentsIndexEntryValue
from core_client.model.non_fungible_vault_contents_index_entry_substate_all_of import NonFungibleVaultContentsIndexEntrySubstateAllOf


class TestNonFungibleVaultContentsIndexEntrySubstateAllOf(unittest.TestCase):
    """NonFungibleVaultContentsIndexEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleVaultContentsIndexEntrySubstateAllOf(self):
        """Test NonFungibleVaultContentsIndexEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleVaultContentsIndexEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
