"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.field_schema_feature_condition_if_own_feature_all_of import FieldSchemaFeatureConditionIfOwnFeatureAllOf


class TestFieldSchemaFeatureConditionIfOwnFeatureAllOf(unittest.TestCase):
    """FieldSchemaFeatureConditionIfOwnFeatureAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldSchemaFeatureConditionIfOwnFeatureAllOf(self):
        """Test FieldSchemaFeatureConditionIfOwnFeatureAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldSchemaFeatureConditionIfOwnFeatureAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
