"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fungible_resource_manager_field_total_supply_value import FungibleResourceManagerFieldTotalSupplyValue
globals()['FungibleResourceManagerFieldTotalSupplyValue'] = FungibleResourceManagerFieldTotalSupplyValue
from core_client.model.fungible_resource_manager_field_total_supply_substate_all_of import FungibleResourceManagerFieldTotalSupplySubstateAllOf


class TestFungibleResourceManagerFieldTotalSupplySubstateAllOf(unittest.TestCase):
    """FungibleResourceManagerFieldTotalSupplySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFungibleResourceManagerFieldTotalSupplySubstateAllOf(self):
        """Test FungibleResourceManagerFieldTotalSupplySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FungibleResourceManagerFieldTotalSupplySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
