"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.scrypto_schema import ScryptoSchema
globals()['ScryptoSchema'] = ScryptoSchema
from core_client.model.schema_entry_value import SchemaEntryValue


class TestSchemaEntryValue(unittest.TestCase):
    """SchemaEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchemaEntryValue(self):
        """Test SchemaEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SchemaEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
