"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_submit_error_details import LtsTransactionSubmitErrorDetails
globals()['LtsTransactionSubmitErrorDetails'] = LtsTransactionSubmitErrorDetails
from core_client.model.lts_transaction_submit_error_response_all_of import LtsTransactionSubmitErrorResponseAllOf


class TestLtsTransactionSubmitErrorResponseAllOf(unittest.TestCase):
    """LtsTransactionSubmitErrorResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitErrorResponseAllOf(self):
        """Test LtsTransactionSubmitErrorResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitErrorResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
