"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.epoch_change_condition import EpochChangeCondition
globals()['EpochChangeCondition'] = EpochChangeCondition
from core_client.model.consensus_manager_field_config_value import ConsensusManagerFieldConfigValue


class TestConsensusManagerFieldConfigValue(unittest.TestCase):
    """ConsensusManagerFieldConfigValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldConfigValue(self):
        """Test ConsensusManagerFieldConfigValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldConfigValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
