"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.substate_type import SubstateType


class TestSubstateType(unittest.TestCase):
    """SubstateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubstateType(self):
        """Test SubstateType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubstateType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
