"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.state_package_request import StatePackageRequest


class TestStatePackageRequest(unittest.TestCase):
    """StatePackageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatePackageRequest(self):
        """Test StatePackageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatePackageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
