"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.package_schema_entry_value import PackageSchemaEntryValue
from core_client.model.schema_key import SchemaKey
globals()['PackageSchemaEntryValue'] = PackageSchemaEntryValue
globals()['SchemaKey'] = SchemaKey
from core_client.model.package_schema_entry_substate_all_of import PackageSchemaEntrySubstateAllOf


class TestPackageSchemaEntrySubstateAllOf(unittest.TestCase):
    """PackageSchemaEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageSchemaEntrySubstateAllOf(self):
        """Test PackageSchemaEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageSchemaEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
