"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.notarized_transaction_hash import NotarizedTransactionHash
globals()['NotarizedTransactionHash'] = NotarizedTransactionHash
from core_client.model.mempool_transaction_response_payloads import MempoolTransactionResponsePayloads


class TestMempoolTransactionResponsePayloads(unittest.TestCase):
    """MempoolTransactionResponsePayloads unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMempoolTransactionResponsePayloads(self):
        """Test MempoolTransactionResponsePayloads"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MempoolTransactionResponsePayloads()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
