"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_tracker_transaction_status import TransactionTrackerTransactionStatus


class TestTransactionTrackerTransactionStatus(unittest.TestCase):
    """TransactionTrackerTransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionTrackerTransactionStatus(self):
        """Test TransactionTrackerTransactionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionTrackerTransactionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
