"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instance_schema_blueprint_type_reference_all_of import InstanceSchemaBlueprintTypeReferenceAllOf


class TestInstanceSchemaBlueprintTypeReferenceAllOf(unittest.TestCase):
    """InstanceSchemaBlueprintTypeReferenceAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceSchemaBlueprintTypeReferenceAllOf(self):
        """Test InstanceSchemaBlueprintTypeReferenceAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceSchemaBlueprintTypeReferenceAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
