"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_version_key import BlueprintVersionKey
from core_client.model.package_blueprint_auth_template_entry_value import PackageBlueprintAuthTemplateEntryValue
globals()['BlueprintVersionKey'] = BlueprintVersionKey
globals()['PackageBlueprintAuthTemplateEntryValue'] = PackageBlueprintAuthTemplateEntryValue
from core_client.model.package_blueprint_auth_template_entry_substate_all_of import PackageBlueprintAuthTemplateEntrySubstateAllOf


class TestPackageBlueprintAuthTemplateEntrySubstateAllOf(unittest.TestCase):
    """PackageBlueprintAuthTemplateEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageBlueprintAuthTemplateEntrySubstateAllOf(self):
        """Test PackageBlueprintAuthTemplateEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageBlueprintAuthTemplateEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
