"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.substate import Substate
globals()['Substate'] = Substate
from core_client.model.state_non_fungible_response import StateNonFungibleResponse


class TestStateNonFungibleResponse(unittest.TestCase):
    """StateNonFungibleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateNonFungibleResponse(self):
        """Test StateNonFungibleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateNonFungibleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
