"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.default_deposit_rule import DefaultDepositRule
from core_client.model.ledger_header_summary import LedgerHeaderSummary
from core_client.model.resource_specific_deposit_behaviour import ResourceSpecificDepositBehaviour
from core_client.model.state_version import StateVersion
globals()['DefaultDepositRule'] = DefaultDepositRule
globals()['LedgerHeaderSummary'] = LedgerHeaderSummary
globals()['ResourceSpecificDepositBehaviour'] = ResourceSpecificDepositBehaviour
globals()['StateVersion'] = StateVersion
from core_client.model.lts_state_account_deposit_behaviour_response import LtsStateAccountDepositBehaviourResponse


class TestLtsStateAccountDepositBehaviourResponse(unittest.TestCase):
    """LtsStateAccountDepositBehaviourResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsStateAccountDepositBehaviourResponse(self):
        """Test LtsStateAccountDepositBehaviourResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsStateAccountDepositBehaviourResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
