"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fully_scoped_type_id import FullyScopedTypeId
globals()['FullyScopedTypeId'] = FullyScopedTypeId
from core_client.model.key_value_store_entry_structure_all_of import KeyValueStoreEntryStructureAllOf


class TestKeyValueStoreEntryStructureAllOf(unittest.TestCase):
    """KeyValueStoreEntryStructureAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValueStoreEntryStructureAllOf(self):
        """Test KeyValueStoreEntryStructureAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyValueStoreEntryStructureAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
