"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.method_accessibility import MethodAccessibility
from core_client.model.role_details import RoleDetails
from core_client.model.role_specification import RoleSpecification
globals()['MethodAccessibility'] = MethodAccessibility
globals()['RoleDetails'] = RoleDetails
globals()['RoleSpecification'] = RoleSpecification
from core_client.model.static_role_definition_auth_template import StaticRoleDefinitionAuthTemplate


class TestStaticRoleDefinitionAuthTemplate(unittest.TestCase):
    """StaticRoleDefinitionAuthTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaticRoleDefinitionAuthTemplate(self):
        """Test StaticRoleDefinitionAuthTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaticRoleDefinitionAuthTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
