"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.one_resource_pool_field_state_value import OneResourcePoolFieldStateValue
globals()['OneResourcePoolFieldStateValue'] = OneResourcePoolFieldStateValue
from core_client.model.one_resource_pool_field_state_substate_all_of import OneResourcePoolFieldStateSubstateAllOf


class TestOneResourcePoolFieldStateSubstateAllOf(unittest.TestCase):
    """OneResourcePoolFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneResourcePoolFieldStateSubstateAllOf(self):
        """Test OneResourcePoolFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OneResourcePoolFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
