"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.local_non_fungible_key import LocalNonFungibleKey
from core_client.model.non_fungible_resource_manager_data_entry_value import NonFungibleResourceManagerDataEntryValue
globals()['LocalNonFungibleKey'] = LocalNonFungibleKey
globals()['NonFungibleResourceManagerDataEntryValue'] = NonFungibleResourceManagerDataEntryValue
from core_client.model.non_fungible_resource_manager_data_entry_substate_all_of import NonFungibleResourceManagerDataEntrySubstateAllOf


class TestNonFungibleResourceManagerDataEntrySubstateAllOf(unittest.TestCase):
    """NonFungibleResourceManagerDataEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleResourceManagerDataEntrySubstateAllOf(self):
        """Test NonFungibleResourceManagerDataEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleResourceManagerDataEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
