"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.intent_hash import IntentHash
from core_client.model.notarized_transaction_hash import NotarizedTransactionHash
globals()['IntentHash'] = IntentHash
globals()['NotarizedTransactionHash'] = NotarizedTransactionHash
from core_client.model.mempool_transaction_hashes import MempoolTransactionHashes


class TestMempoolTransactionHashes(unittest.TestCase):
    """MempoolTransactionHashes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMempoolTransactionHashes(self):
        """Test MempoolTransactionHashes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MempoolTransactionHashes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
