"""
    Radix System API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import system_client
from system_client.model.address import Address
globals()['Address'] = Address
from system_client.model.address_book_entry import AddressBookEntry


class TestAddressBookEntry(unittest.TestCase):
    """AddressBookEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressBookEntry(self):
        """Test AddressBookEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddressBookEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
