"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_submit_error_details import TransactionSubmitErrorDetails
globals()['TransactionSubmitErrorDetails'] = TransactionSubmitErrorDetails
from core_client.model.transaction_submit_error_response_all_of import TransactionSubmitErrorResponseAllOf


class TestTransactionSubmitErrorResponseAllOf(unittest.TestCase):
    """TransactionSubmitErrorResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSubmitErrorResponseAllOf(self):
        """Test TransactionSubmitErrorResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionSubmitErrorResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
