"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.local_type_index import LocalTypeIndex
from core_client.model.schema_hash import SchemaHash
globals()['LocalTypeIndex'] = LocalTypeIndex
globals()['SchemaHash'] = SchemaHash
from core_client.model.package_type_pointer_all_of import PackageTypePointerAllOf


class TestPackageTypePointerAllOf(unittest.TestCase):
    """PackageTypePointerAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageTypePointerAllOf(self):
        """Test PackageTypePointerAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageTypePointerAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
