"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_submit_error_details_type import TransactionSubmitErrorDetailsType


class TestTransactionSubmitErrorDetailsType(unittest.TestCase):
    """TransactionSubmitErrorDetailsType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSubmitErrorDetailsType(self):
        """Test TransactionSubmitErrorDetailsType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionSubmitErrorDetailsType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
