"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.consensus_manager_field_current_time_value import ConsensusManagerFieldCurrentTimeValue
globals()['ConsensusManagerFieldCurrentTimeValue'] = ConsensusManagerFieldCurrentTimeValue
from core_client.model.consensus_manager_field_current_time_substate_all_of import ConsensusManagerFieldCurrentTimeSubstateAllOf


class TestConsensusManagerFieldCurrentTimeSubstateAllOf(unittest.TestCase):
    """ConsensusManagerFieldCurrentTimeSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldCurrentTimeSubstateAllOf(self):
        """Test ConsensusManagerFieldCurrentTimeSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldCurrentTimeSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
