"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule import AccessRule
from core_client.model.access_rule_type import AccessRuleType
from core_client.model.allow_all_access_rule import AllowAllAccessRule
from core_client.model.deny_all_access_rule import DenyAllAccessRule
from core_client.model.protected_access_rule import ProtectedAccessRule
globals()['AccessRule'] = AccessRule
globals()['AccessRuleType'] = AccessRuleType
globals()['AllowAllAccessRule'] = AllowAllAccessRule
globals()['DenyAllAccessRule'] = DenyAllAccessRule
globals()['ProtectedAccessRule'] = ProtectedAccessRule
from core_client.model.deny_all_access_rule import DenyAllAccessRule


class TestDenyAllAccessRule(unittest.TestCase):
    """DenyAllAccessRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDenyAllAccessRule(self):
        """Test DenyAllAccessRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DenyAllAccessRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
