"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.resource_preference import ResourcePreference
globals()['ResourcePreference'] = ResourcePreference
from core_client.model.account_resource_preference_entry_value import AccountResourcePreferenceEntryValue


class TestAccountResourcePreferenceEntryValue(unittest.TestCase):
    """AccountResourcePreferenceEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountResourcePreferenceEntryValue(self):
        """Test AccountResourcePreferenceEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountResourcePreferenceEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
