"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ledger_transaction import LedgerTransaction
from core_client.model.parsed_ledger_transaction import ParsedLedgerTransaction
from core_client.model.parsed_ledger_transaction_all_of import ParsedLedgerTransactionAllOf
from core_client.model.parsed_ledger_transaction_identifiers import ParsedLedgerTransactionIdentifiers
from core_client.model.parsed_notarized_transaction import ParsedNotarizedTransaction
from core_client.model.parsed_signed_transaction_intent import ParsedSignedTransactionIntent
from core_client.model.parsed_transaction import ParsedTransaction
from core_client.model.parsed_transaction_intent import ParsedTransactionIntent
from core_client.model.parsed_transaction_type import ParsedTransactionType
globals()['LedgerTransaction'] = LedgerTransaction
globals()['ParsedLedgerTransaction'] = ParsedLedgerTransaction
globals()['ParsedLedgerTransactionAllOf'] = ParsedLedgerTransactionAllOf
globals()['ParsedLedgerTransactionIdentifiers'] = ParsedLedgerTransactionIdentifiers
globals()['ParsedNotarizedTransaction'] = ParsedNotarizedTransaction
globals()['ParsedSignedTransactionIntent'] = ParsedSignedTransactionIntent
globals()['ParsedTransaction'] = ParsedTransaction
globals()['ParsedTransactionIntent'] = ParsedTransactionIntent
globals()['ParsedTransactionType'] = ParsedTransactionType
from core_client.model.parsed_ledger_transaction import ParsedLedgerTransaction


class TestParsedLedgerTransaction(unittest.TestCase):
    """ParsedLedgerTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedLedgerTransaction(self):
        """Test ParsedLedgerTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedLedgerTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
