"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instance_type_pointer import InstanceTypePointer
from core_client.model.local_type_index import LocalTypeIndex
from core_client.model.package_type_pointer import PackageTypePointer
from core_client.model.package_type_pointer_all_of import PackageTypePointerAllOf
from core_client.model.schema_hash import SchemaHash
from core_client.model.type_pointer import TypePointer
from core_client.model.type_pointer_type import TypePointerType
globals()['InstanceTypePointer'] = InstanceTypePointer
globals()['LocalTypeIndex'] = LocalTypeIndex
globals()['PackageTypePointer'] = PackageTypePointer
globals()['PackageTypePointerAllOf'] = PackageTypePointerAllOf
globals()['SchemaHash'] = SchemaHash
globals()['TypePointer'] = TypePointer
globals()['TypePointerType'] = TypePointerType
from core_client.model.package_type_pointer import PackageTypePointer


class TestPackageTypePointer(unittest.TestCase):
    """PackageTypePointer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageTypePointer(self):
        """Test PackageTypePointer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageTypePointer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
