"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.partition_description_type import PartitionDescriptionType


class TestPartitionDescriptionType(unittest.TestCase):
    """PartitionDescriptionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartitionDescriptionType(self):
        """Test PartitionDescriptionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartitionDescriptionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
