"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.validator_fee_change_request import ValidatorFeeChangeRequest


class TestValidatorFeeChangeRequest(unittest.TestCase):
    """ValidatorFeeChangeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidatorFeeChangeRequest(self):
        """Test ValidatorFeeChangeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidatorFeeChangeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
