"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_resource_manager_field_total_supply_value import NonFungibleResourceManagerFieldTotalSupplyValue


class TestNonFungibleResourceManagerFieldTotalSupplyValue(unittest.TestCase):
    """NonFungibleResourceManagerFieldTotalSupplyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleResourceManagerFieldTotalSupplyValue(self):
        """Test NonFungibleResourceManagerFieldTotalSupplyValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleResourceManagerFieldTotalSupplyValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
