"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_intent_status import LtsTransactionIntentStatus
from core_client.model.lts_transaction_payload_details import LtsTransactionPayloadDetails
from core_client.model.state_version import StateVersion
globals()['LtsTransactionIntentStatus'] = LtsTransactionIntentStatus
globals()['LtsTransactionPayloadDetails'] = LtsTransactionPayloadDetails
globals()['StateVersion'] = StateVersion
from core_client.model.lts_transaction_status_response import LtsTransactionStatusResponse


class TestLtsTransactionStatusResponse(unittest.TestCase):
    """LtsTransactionStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionStatusResponse(self):
        """Test LtsTransactionStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
