"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule import AccessRule
from core_client.model.owner_role_updater import OwnerRoleUpdater
globals()['AccessRule'] = AccessRule
globals()['OwnerRoleUpdater'] = OwnerRoleUpdater
from core_client.model.owner_role import OwnerRole


class TestOwnerRole(unittest.TestCase):
    """OwnerRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnerRole(self):
        """Test OwnerRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwnerRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
