"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.target_identifier import TargetIdentifier
globals()['TargetIdentifier'] = TargetIdentifier
from core_client.model.transaction_call_preview_request import TransactionCallPreviewRequest


class TestTransactionCallPreviewRequest(unittest.TestCase):
    """TransactionCallPreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCallPreviewRequest(self):
        """Test TransactionCallPreviewRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCallPreviewRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
