"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.type_info_module_field_type_info_value import TypeInfoModuleFieldTypeInfoValue
globals()['TypeInfoModuleFieldTypeInfoValue'] = TypeInfoModuleFieldTypeInfoValue
from core_client.model.type_info_module_field_type_info_substate_all_of import TypeInfoModuleFieldTypeInfoSubstateAllOf


class TestTypeInfoModuleFieldTypeInfoSubstateAllOf(unittest.TestCase):
    """TypeInfoModuleFieldTypeInfoSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeInfoModuleFieldTypeInfoSubstateAllOf(self):
        """Test TypeInfoModuleFieldTypeInfoSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypeInfoModuleFieldTypeInfoSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
