"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.state_version import StateVersion
globals()['StateVersion'] = StateVersion
from core_client.model.requested_state_version_out_of_bounds_error_details_all_of import RequestedStateVersionOutOfBoundsErrorDetailsAllOf


class TestRequestedStateVersionOutOfBoundsErrorDetailsAllOf(unittest.TestCase):
    """RequestedStateVersionOutOfBoundsErrorDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestedStateVersionOutOfBoundsErrorDetailsAllOf(self):
        """Test RequestedStateVersionOutOfBoundsErrorDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestedStateVersionOutOfBoundsErrorDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
