"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_fee_fungible_resource_balance_change_type import LtsFeeFungibleResourceBalanceChangeType
globals()['LtsFeeFungibleResourceBalanceChangeType'] = LtsFeeFungibleResourceBalanceChangeType
from core_client.model.lts_fee_fungible_resource_balance_change import LtsFeeFungibleResourceBalanceChange


class TestLtsFeeFungibleResourceBalanceChange(unittest.TestCase):
    """LtsFeeFungibleResourceBalanceChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsFeeFungibleResourceBalanceChange(self):
        """Test LtsFeeFungibleResourceBalanceChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsFeeFungibleResourceBalanceChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
