"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.intent_hash import IntentHash
from core_client.model.transaction_header import TransactionHeader
from core_client.model.transaction_message import TransactionMessage
globals()['IntentHash'] = IntentHash
globals()['TransactionHeader'] = TransactionHeader
globals()['TransactionMessage'] = TransactionMessage
from core_client.model.transaction_intent import TransactionIntent


class TestTransactionIntent(unittest.TestCase):
    """TransactionIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionIntent(self):
        """Test TransactionIntent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionIntent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
