"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.parsed_transaction_intent_identifiers import ParsedTransactionIntentIdentifiers
from core_client.model.transaction_intent import TransactionIntent
globals()['ParsedTransactionIntentIdentifiers'] = ParsedTransactionIntentIdentifiers
globals()['TransactionIntent'] = TransactionIntent
from core_client.model.parsed_transaction_intent_all_of import ParsedTransactionIntentAllOf


class TestParsedTransactionIntentAllOf(unittest.TestCase):
    """ParsedTransactionIntentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedTransactionIntentAllOf(self):
        """Test ParsedTransactionIntentAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedTransactionIntentAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
