"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
globals()['EntityReference'] = EntityReference
from core_client.model.account_vault_index_entry_value import AccountVaultIndexEntryValue


class TestAccountVaultIndexEntryValue(unittest.TestCase):
    """AccountVaultIndexEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountVaultIndexEntryValue(self):
        """Test AccountVaultIndexEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountVaultIndexEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
