"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.notarized_transaction import NotarizedTransaction
globals()['NotarizedTransaction'] = NotarizedTransaction
from core_client.model.user_ledger_transaction_all_of import UserLedgerTransactionAllOf


class TestUserLedgerTransactionAllOf(unittest.TestCase):
    """UserLedgerTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLedgerTransactionAllOf(self):
        """Test UserLedgerTransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserLedgerTransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
