"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_vault_contents_index_entry_value import NonFungibleVaultContentsIndexEntryValue


class TestNonFungibleVaultContentsIndexEntryValue(unittest.TestCase):
    """NonFungibleVaultContentsIndexEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleVaultContentsIndexEntryValue(self):
        """Test NonFungibleVaultContentsIndexEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleVaultContentsIndexEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
