"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.notarized_transaction_hash import NotarizedTransactionHash
from core_client.model.state_version import StateVersion
from core_client.model.transaction_payload_status import TransactionPayloadStatus
globals()['NotarizedTransactionHash'] = NotarizedTransactionHash
globals()['StateVersion'] = StateVersion
globals()['TransactionPayloadStatus'] = TransactionPayloadStatus
from core_client.model.transaction_payload_details import TransactionPayloadDetails


class TestTransactionPayloadDetails(unittest.TestCase):
    """TransactionPayloadDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionPayloadDetails(self):
        """Test TransactionPayloadDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionPayloadDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
