"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.payment_from_vault import PaymentFromVault
globals()['PaymentFromVault'] = PaymentFromVault
from core_client.model.fee_source import FeeSource


class TestFeeSource(unittest.TestCase):
    """FeeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeSource(self):
        """Test FeeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FeeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
