"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.owner_role import OwnerRole
globals()['OwnerRole'] = OwnerRole
from core_client.model.access_rules_module_field_owner_role_value import AccessRulesModuleFieldOwnerRoleValue


class TestAccessRulesModuleFieldOwnerRoleValue(unittest.TestCase):
    """AccessRulesModuleFieldOwnerRoleValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRulesModuleFieldOwnerRoleValue(self):
        """Test AccessRulesModuleFieldOwnerRoleValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRulesModuleFieldOwnerRoleValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
