"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.round_update_transaction import RoundUpdateTransaction
globals()['RoundUpdateTransaction'] = RoundUpdateTransaction
from core_client.model.round_update_ledger_transaction_all_of import RoundUpdateLedgerTransactionAllOf


class TestRoundUpdateLedgerTransactionAllOf(unittest.TestCase):
    """RoundUpdateLedgerTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoundUpdateLedgerTransactionAllOf(self):
        """Test RoundUpdateLedgerTransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoundUpdateLedgerTransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
