"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.presented_badge import PresentedBadge
globals()['PresentedBadge'] = PresentedBadge
from core_client.model.lts_state_account_deposit_behaviour_request import LtsStateAccountDepositBehaviourRequest


class TestLtsStateAccountDepositBehaviourRequest(unittest.TestCase):
    """LtsStateAccountDepositBehaviourRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsStateAccountDepositBehaviourRequest(self):
        """Test LtsStateAccountDepositBehaviourRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsStateAccountDepositBehaviourRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
