"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_submit_request import LtsTransactionSubmitRequest


class TestLtsTransactionSubmitRequest(unittest.TestCase):
    """LtsTransactionSubmitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitRequest(self):
        """Test LtsTransactionSubmitRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
