"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_status import TransactionStatus


class TestTransactionStatus(unittest.TestCase):
    """TransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatus(self):
        """Test TransactionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
