"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
globals()['EntityReference'] = EntityReference
from core_client.model.payment_from_vault import PaymentFromVault


class TestPaymentFromVault(unittest.TestCase):
    """PaymentFromVault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentFromVault(self):
        """Test PaymentFromVault"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentFromVault()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
