"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.attached_module_id import AttachedModuleId
globals()['AttachedModuleId'] = AttachedModuleId
from core_client.model.module_version import ModuleVersion


class TestModuleVersion(unittest.TestCase):
    """ModuleVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModuleVersion(self):
        """Test ModuleVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModuleVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
