"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.main_method_key import MainMethodKey
from core_client.model.royalty_module_method_royalty_entry_value import RoyaltyModuleMethodRoyaltyEntryValue
globals()['MainMethodKey'] = MainMethodKey
globals()['RoyaltyModuleMethodRoyaltyEntryValue'] = RoyaltyModuleMethodRoyaltyEntryValue
from core_client.model.royalty_module_method_royalty_entry_substate_all_of import RoyaltyModuleMethodRoyaltyEntrySubstateAllOf


class TestRoyaltyModuleMethodRoyaltyEntrySubstateAllOf(unittest.TestCase):
    """RoyaltyModuleMethodRoyaltyEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoyaltyModuleMethodRoyaltyEntrySubstateAllOf(self):
        """Test RoyaltyModuleMethodRoyaltyEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoyaltyModuleMethodRoyaltyEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
