"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.royalty_amount import RoyaltyAmount
globals()['RoyaltyAmount'] = RoyaltyAmount
from core_client.model.royalty_module_method_royalty_entry_value import RoyaltyModuleMethodRoyaltyEntryValue


class TestRoyaltyModuleMethodRoyaltyEntryValue(unittest.TestCase):
    """RoyaltyModuleMethodRoyaltyEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoyaltyModuleMethodRoyaltyEntryValue(self):
        """Test RoyaltyModuleMethodRoyaltyEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoyaltyModuleMethodRoyaltyEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
