"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.pending_owner_stake_withdrawal import PendingOwnerStakeWithdrawal


class TestPendingOwnerStakeWithdrawal(unittest.TestCase):
    """PendingOwnerStakeWithdrawal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPendingOwnerStakeWithdrawal(self):
        """Test PendingOwnerStakeWithdrawal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PendingOwnerStakeWithdrawal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
