"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.scenarios_request import ScenariosRequest


class TestScenariosRequest(unittest.TestCase):
    """ScenariosRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenariosRequest(self):
        """Test ScenariosRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScenariosRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
