"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.parsed_ledger_transaction import ParsedLedgerTransaction
from core_client.model.parsed_notarized_transaction import ParsedNotarizedTransaction
from core_client.model.parsed_signed_transaction_intent import ParsedSignedTransactionIntent
from core_client.model.parsed_signed_transaction_intent_all_of import ParsedSignedTransactionIntentAllOf
from core_client.model.parsed_signed_transaction_intent_identifiers import ParsedSignedTransactionIntentIdentifiers
from core_client.model.parsed_transaction import ParsedTransaction
from core_client.model.parsed_transaction_intent import ParsedTransactionIntent
from core_client.model.parsed_transaction_type import ParsedTransactionType
from core_client.model.signed_transaction_intent import SignedTransactionIntent
globals()['ParsedLedgerTransaction'] = ParsedLedgerTransaction
globals()['ParsedNotarizedTransaction'] = ParsedNotarizedTransaction
globals()['ParsedSignedTransactionIntent'] = ParsedSignedTransactionIntent
globals()['ParsedSignedTransactionIntentAllOf'] = ParsedSignedTransactionIntentAllOf
globals()['ParsedSignedTransactionIntentIdentifiers'] = ParsedSignedTransactionIntentIdentifiers
globals()['ParsedTransaction'] = ParsedTransaction
globals()['ParsedTransactionIntent'] = ParsedTransactionIntent
globals()['ParsedTransactionType'] = ParsedTransactionType
globals()['SignedTransactionIntent'] = SignedTransactionIntent
from core_client.model.parsed_signed_transaction_intent import ParsedSignedTransactionIntent


class TestParsedSignedTransactionIntent(unittest.TestCase):
    """ParsedSignedTransactionIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedSignedTransactionIntent(self):
        """Test ParsedSignedTransactionIntent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedSignedTransactionIntent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
