"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rules_module_field_owner_role_value import AccessRulesModuleFieldOwnerRoleValue
globals()['AccessRulesModuleFieldOwnerRoleValue'] = AccessRulesModuleFieldOwnerRoleValue
from core_client.model.access_rules_module_field_owner_role_substate_all_of import AccessRulesModuleFieldOwnerRoleSubstateAllOf


class TestAccessRulesModuleFieldOwnerRoleSubstateAllOf(unittest.TestCase):
    """AccessRulesModuleFieldOwnerRoleSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRulesModuleFieldOwnerRoleSubstateAllOf(self):
        """Test AccessRulesModuleFieldOwnerRoleSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRulesModuleFieldOwnerRoleSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
