"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_schema_blueprint_type_reference import BlueprintSchemaBlueprintTypeReference
from core_client.model.blueprint_type_reference_kind import BlueprintTypeReferenceKind
from core_client.model.instance_schema_blueprint_type_reference import InstanceSchemaBlueprintTypeReference
globals()['BlueprintSchemaBlueprintTypeReference'] = BlueprintSchemaBlueprintTypeReference
globals()['BlueprintTypeReferenceKind'] = BlueprintTypeReferenceKind
globals()['InstanceSchemaBlueprintTypeReference'] = InstanceSchemaBlueprintTypeReference
from core_client.model.blueprint_type_reference import BlueprintTypeReference


class TestBlueprintTypeReference(unittest.TestCase):
    """BlueprintTypeReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintTypeReference(self):
        """Test BlueprintTypeReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintTypeReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
