"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_type import EntityType
globals()['EntityType'] = EntityType
from core_client.model.entity_reference import EntityReference


class TestEntityReference(unittest.TestCase):
    """EntityReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityReference(self):
        """Test EntityReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
