"""
    Radix Core API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_identifier import TransactionIdentifier
globals()['TransactionIdentifier'] = TransactionIdentifier
from core_client.model.update_vote_response import UpdateVoteResponse


class TestUpdateVoteResponse(unittest.TestCase):
    """UpdateVoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateVoteResponse(self):
        """Test UpdateVoteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateVoteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
