"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.generic_type_parameter_constraints import GenericTypeParameterConstraints


class TestGenericTypeParameterConstraints(unittest.TestCase):
    """GenericTypeParameterConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericTypeParameterConstraints(self):
        """Test GenericTypeParameterConstraints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericTypeParameterConstraints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
