"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.pool_vault import PoolVault
globals()['PoolVault'] = PoolVault
from core_client.model.multi_resource_pool_field_state_value import MultiResourcePoolFieldStateValue


class TestMultiResourcePoolFieldStateValue(unittest.TestCase):
    """MultiResourcePoolFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiResourcePoolFieldStateValue(self):
        """Test MultiResourcePoolFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiResourcePoolFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
