"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
globals()['EntityReference'] = EntityReference
from core_client.model.state_component_descendent_node import StateComponentDescendentNode


class TestStateComponentDescendentNode(unittest.TestCase):
    """StateComponentDescendentNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateComponentDescendentNode(self):
        """Test StateComponentDescendentNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateComponentDescendentNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
