"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.active_validator import ActiveValidator
globals()['ActiveValidator'] = ActiveValidator
from core_client.model.next_epoch import NextEpoch


class TestNextEpoch(unittest.TestCase):
    """NextEpoch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNextEpoch(self):
        """Test NextEpoch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NextEpoch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
