"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instant import Instant
from core_client.model.lts_transaction_submit_rejected_error_details_all_of import LtsTransactionSubmitRejectedErrorDetailsAllOf
from core_client.model.transaction_submit_error_details import TransactionSubmitErrorDetails
from core_client.model.transaction_submit_error_details_type import TransactionSubmitErrorDetailsType
from core_client.model.transaction_submit_priority_threshold_not_met_error_details import TransactionSubmitPriorityThresholdNotMetErrorDetails
from core_client.model.transaction_submit_rejected_error_details import TransactionSubmitRejectedErrorDetails
globals()['Instant'] = Instant
globals()['LtsTransactionSubmitRejectedErrorDetailsAllOf'] = LtsTransactionSubmitRejectedErrorDetailsAllOf
globals()['TransactionSubmitErrorDetails'] = TransactionSubmitErrorDetails
globals()['TransactionSubmitErrorDetailsType'] = TransactionSubmitErrorDetailsType
globals()['TransactionSubmitPriorityThresholdNotMetErrorDetails'] = TransactionSubmitPriorityThresholdNotMetErrorDetails
globals()['TransactionSubmitRejectedErrorDetails'] = TransactionSubmitRejectedErrorDetails
from core_client.model.transaction_submit_rejected_error_details import TransactionSubmitRejectedErrorDetails


class TestTransactionSubmitRejectedErrorDetails(unittest.TestCase):
    """TransactionSubmitRejectedErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSubmitRejectedErrorDetails(self):
        """Test TransactionSubmitRejectedErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionSubmitRejectedErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
