"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.epoch_round import EpochRound
from core_client.model.instant import Instant
from core_client.model.ledger_hashes import LedgerHashes
globals()['EpochRound'] = EpochRound
globals()['Instant'] = Instant
globals()['LedgerHashes'] = LedgerHashes
from core_client.model.ledger_header_summary import LedgerHeaderSummary


class TestLedgerHeaderSummary(unittest.TestCase):
    """LedgerHeaderSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLedgerHeaderSummary(self):
        """Test LedgerHeaderSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LedgerHeaderSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
