"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.committed_intent_metadata import CommittedIntentMetadata
from core_client.model.lts_transaction_submit_intent_already_committed_all_of import LtsTransactionSubmitIntentAlreadyCommittedAllOf
from core_client.model.transaction_submit_error_details import TransactionSubmitErrorDetails
from core_client.model.transaction_submit_error_details_type import TransactionSubmitErrorDetailsType
from core_client.model.transaction_submit_intent_already_committed import TransactionSubmitIntentAlreadyCommitted
from core_client.model.transaction_submit_priority_threshold_not_met_error_details import TransactionSubmitPriorityThresholdNotMetErrorDetails
from core_client.model.transaction_submit_rejected_error_details import TransactionSubmitRejectedErrorDetails
globals()['CommittedIntentMetadata'] = CommittedIntentMetadata
globals()['LtsTransactionSubmitIntentAlreadyCommittedAllOf'] = LtsTransactionSubmitIntentAlreadyCommittedAllOf
globals()['TransactionSubmitErrorDetails'] = TransactionSubmitErrorDetails
globals()['TransactionSubmitErrorDetailsType'] = TransactionSubmitErrorDetailsType
globals()['TransactionSubmitIntentAlreadyCommitted'] = TransactionSubmitIntentAlreadyCommitted
globals()['TransactionSubmitPriorityThresholdNotMetErrorDetails'] = TransactionSubmitPriorityThresholdNotMetErrorDetails
globals()['TransactionSubmitRejectedErrorDetails'] = TransactionSubmitRejectedErrorDetails
from core_client.model.transaction_submit_intent_already_committed import TransactionSubmitIntentAlreadyCommitted


class TestTransactionSubmitIntentAlreadyCommitted(unittest.TestCase):
    """TransactionSubmitIntentAlreadyCommitted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSubmitIntentAlreadyCommitted(self):
        """Test TransactionSubmitIntentAlreadyCommitted"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionSubmitIntentAlreadyCommitted()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
