"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.transaction_id_key import TransactionIdKey
from core_client.model.transaction_tracker_collection_entry_value import TransactionTrackerCollectionEntryValue
globals()['TransactionIdKey'] = TransactionIdKey
globals()['TransactionTrackerCollectionEntryValue'] = TransactionTrackerCollectionEntryValue
from core_client.model.transaction_tracker_collection_entry_substate_all_of import TransactionTrackerCollectionEntrySubstateAllOf


class TestTransactionTrackerCollectionEntrySubstateAllOf(unittest.TestCase):
    """TransactionTrackerCollectionEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionTrackerCollectionEntrySubstateAllOf(self):
        """Test TransactionTrackerCollectionEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionTrackerCollectionEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
