"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_vault_field_balance_value import NonFungibleVaultFieldBalanceValue


class TestNonFungibleVaultFieldBalanceValue(unittest.TestCase):
    """NonFungibleVaultFieldBalanceValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleVaultFieldBalanceValue(self):
        """Test NonFungibleVaultFieldBalanceValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleVaultFieldBalanceValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
