"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.event_emitter_identifier_type import EventEmitterIdentifierType


class TestEventEmitterIdentifierType(unittest.TestCase):
    """EventEmitterIdentifierType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventEmitterIdentifierType(self):
        """Test EventEmitterIdentifierType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventEmitterIdentifierType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
