"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_type_identifier import BlueprintTypeIdentifier
from core_client.model.fully_scoped_type_id import FullyScopedTypeId
globals()['BlueprintTypeIdentifier'] = BlueprintTypeIdentifier
globals()['FullyScopedTypeId'] = FullyScopedTypeId
from core_client.model.remote_generic_substitution_all_of import RemoteGenericSubstitutionAllOf


class TestRemoteGenericSubstitutionAllOf(unittest.TestCase):
    """RemoteGenericSubstitutionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteGenericSubstitutionAllOf(self):
        """Test RemoteGenericSubstitutionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteGenericSubstitutionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
