"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instruction_resource_changes import InstructionResourceChanges
from core_client.model.transaction_preview_response_logs import TransactionPreviewResponseLogs
from core_client.model.transaction_receipt import TransactionReceipt
globals()['InstructionResourceChanges'] = InstructionResourceChanges
globals()['TransactionPreviewResponseLogs'] = TransactionPreviewResponseLogs
globals()['TransactionReceipt'] = TransactionReceipt
from core_client.model.transaction_preview_response import TransactionPreviewResponse


class TestTransactionPreviewResponse(unittest.TestCase):
    """TransactionPreviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionPreviewResponse(self):
        """Test TransactionPreviewResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionPreviewResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
