"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instance_schema import InstanceSchema
globals()['InstanceSchema'] = InstanceSchema
from core_client.model.object_type_info_details_all_of import ObjectTypeInfoDetailsAllOf


class TestObjectTypeInfoDetailsAllOf(unittest.TestCase):
    """ObjectTypeInfoDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectTypeInfoDetailsAllOf(self):
        """Test ObjectTypeInfoDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectTypeInfoDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
