"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.ecdsa_secp256k1_public_key import EcdsaSecp256k1PublicKey
from core_client.model.ecdsa_secp256k1_public_key_all_of import EcdsaSecp256k1PublicKeyAllOf
from core_client.model.eddsa_ed25519_public_key import EddsaEd25519PublicKey
from core_client.model.public_key import PublicKey
from core_client.model.public_key_type import PublicKeyType
globals()['EcdsaSecp256k1PublicKey'] = EcdsaSecp256k1PublicKey
globals()['EcdsaSecp256k1PublicKeyAllOf'] = EcdsaSecp256k1PublicKeyAllOf
globals()['EddsaEd25519PublicKey'] = EddsaEd25519PublicKey
globals()['PublicKey'] = PublicKey
globals()['PublicKeyType'] = PublicKeyType
from core_client.model.ecdsa_secp256k1_public_key import EcdsaSecp256k1PublicKey


class TestEcdsaSecp256k1PublicKey(unittest.TestCase):
    """EcdsaSecp256k1PublicKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcdsaSecp256k1PublicKey(self):
        """Test EcdsaSecp256k1PublicKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EcdsaSecp256k1PublicKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
