"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.deposit_rule import DepositRule


class TestDepositRule(unittest.TestCase):
    """DepositRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepositRule(self):
        """Test DepositRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DepositRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
