"""
    Radix System API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import system_client
from system_client.model.health_response_unknown_reported_forks import HealthResponseUnknownReportedForks


class TestHealthResponseUnknownReportedForks(unittest.TestCase):
    """HealthResponseUnknownReportedForks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthResponseUnknownReportedForks(self):
        """Test HealthResponseUnknownReportedForks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HealthResponseUnknownReportedForks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
