"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.costing_parameters import CostingParameters


class TestCostingParameters(unittest.TestCase):
    """CostingParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCostingParameters(self):
        """Test CostingParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CostingParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
