"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import unittest

import core_client
from core_client.api.status_api import StatusApi  # noqa: E501


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_network_configuration_post(self):
        """Test case for status_network_configuration_post

        Get Network Configuration  # noqa: E501
        """
        pass

    def test_status_network_status_post(self):
        """Test case for status_network_status_post

        Get Network Status  # noqa: E501
        """
        pass

    def test_status_scenarios_post(self):
        """Test case for status_scenarios_post

        Get Scenarios' results.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
