"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.generic_key import GenericKey
from core_client.model.generic_key_value_store_entry_value import GenericKeyValueStoreEntryValue
globals()['GenericKey'] = GenericKey
globals()['GenericKeyValueStoreEntryValue'] = GenericKeyValueStoreEntryValue
from core_client.model.generic_key_value_store_entry_substate_all_of import GenericKeyValueStoreEntrySubstateAllOf


class TestGenericKeyValueStoreEntrySubstateAllOf(unittest.TestCase):
    """GenericKeyValueStoreEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericKeyValueStoreEntrySubstateAllOf(self):
        """Test GenericKeyValueStoreEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericKeyValueStoreEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
