"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.field_schema_feature_condition_type import FieldSchemaFeatureConditionType


class TestFieldSchemaFeatureConditionType(unittest.TestCase):
    """FieldSchemaFeatureConditionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldSchemaFeatureConditionType(self):
        """Test FieldSchemaFeatureConditionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldSchemaFeatureConditionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
