"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.role_protected_method_accessibility_all_of import RoleProtectedMethodAccessibilityAllOf


class TestRoleProtectedMethodAccessibilityAllOf(unittest.TestCase):
    """RoleProtectedMethodAccessibilityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleProtectedMethodAccessibilityAllOf(self):
        """Test RoleProtectedMethodAccessibilityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleProtectedMethodAccessibilityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
