"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
from core_client.model.resource_amount import ResourceAmount
globals()['EntityReference'] = EntityReference
globals()['ResourceAmount'] = ResourceAmount
from core_client.model.vault_balance import VaultBalance


class TestVaultBalance(unittest.TestCase):
    """VaultBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVaultBalance(self):
        """Test VaultBalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VaultBalance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
