"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.two_resource_pool_field_state_value import TwoResourcePoolFieldStateValue
globals()['TwoResourcePoolFieldStateValue'] = TwoResourcePoolFieldStateValue
from core_client.model.two_resource_pool_field_state_substate_all_of import TwoResourcePoolFieldStateSubstateAllOf


class TestTwoResourcePoolFieldStateSubstateAllOf(unittest.TestCase):
    """TwoResourcePoolFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwoResourcePoolFieldStateSubstateAllOf(self):
        """Test TwoResourcePoolFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TwoResourcePoolFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
