"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.eddsa_ed25519_public_key_all_of import EddsaEd25519PublicKeyAllOf


class TestEddsaEd25519PublicKeyAllOf(unittest.TestCase):
    """EddsaEd25519PublicKeyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEddsaEd25519PublicKeyAllOf(self):
        """Test EddsaEd25519PublicKeyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EddsaEd25519PublicKeyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
