"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_id_type import NonFungibleIdType
globals()['NonFungibleIdType'] = NonFungibleIdType
from core_client.model.non_fungible_resource_manager_field_id_type_value import NonFungibleResourceManagerFieldIdTypeValue


class TestNonFungibleResourceManagerFieldIdTypeValue(unittest.TestCase):
    """NonFungibleResourceManagerFieldIdTypeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleResourceManagerFieldIdTypeValue(self):
        """Test NonFungibleResourceManagerFieldIdTypeValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleResourceManagerFieldIdTypeValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
