"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.method_accessibility_type import MethodAccessibilityType


class TestMethodAccessibilityType(unittest.TestCase):
    """MethodAccessibilityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodAccessibilityType(self):
        """Test MethodAccessibilityType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MethodAccessibilityType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
