"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_controller_field_state_value import AccessControllerFieldStateValue
globals()['AccessControllerFieldStateValue'] = AccessControllerFieldStateValue
from core_client.model.access_controller_field_state_substate_all_of import AccessControllerFieldStateSubstateAllOf


class TestAccessControllerFieldStateSubstateAllOf(unittest.TestCase):
    """AccessControllerFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessControllerFieldStateSubstateAllOf(self):
        """Test AccessControllerFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessControllerFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
