"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.key_value_store_info import KeyValueStoreInfo
globals()['KeyValueStoreInfo'] = KeyValueStoreInfo
from core_client.model.key_value_store_type_info_details_all_of import KeyValueStoreTypeInfoDetailsAllOf


class TestKeyValueStoreTypeInfoDetailsAllOf(unittest.TestCase):
    """KeyValueStoreTypeInfoDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValueStoreTypeInfoDetailsAllOf(self):
        """Test KeyValueStoreTypeInfoDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeyValueStoreTypeInfoDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
