"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import unittest

import core_client
from core_client.api.lts_api import LTSApi  # noqa: E501


class TestLTSApi(unittest.TestCase):
    """LTSApi unit test stubs"""

    def setUp(self):
        self.api = LTSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lts_state_account_all_fungible_resource_balances_post(self):
        """Test case for lts_state_account_all_fungible_resource_balances_post

        Get All Account Balances  # noqa: E501
        """
        pass

    def test_lts_state_account_fungible_resource_balance_post(self):
        """Test case for lts_state_account_fungible_resource_balance_post

        Get Single Account Balance  # noqa: E501
        """
        pass

    def test_lts_stream_account_transaction_outcomes_post(self):
        """Test case for lts_stream_account_transaction_outcomes_post

        Get Account Transaction Outcomes  # noqa: E501
        """
        pass

    def test_lts_stream_transaction_outcomes_post(self):
        """Test case for lts_stream_transaction_outcomes_post

        Get Transaction Outcomes  # noqa: E501
        """
        pass

    def test_lts_transaction_construction_post(self):
        """Test case for lts_transaction_construction_post

        Get Construction Metadata  # noqa: E501
        """
        pass

    def test_lts_transaction_status_post(self):
        """Test case for lts_transaction_status_post

        Get Transaction Status  # noqa: E501
        """
        pass

    def test_lts_transaction_submit_post(self):
        """Test case for lts_transaction_submit_post

        Submit Transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
