"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
from core_client.model.sbor_data import SborData
globals()['EntityReference'] = EntityReference
globals()['SborData'] = SborData
from core_client.model.data_struct import DataStruct


class TestDataStruct(unittest.TestCase):
    """DataStruct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataStruct(self):
        """Test DataStruct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataStruct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
