"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_schema_blueprint_type_reference import BlueprintSchemaBlueprintTypeReference
from core_client.model.blueprint_schema_blueprint_type_reference_all_of import BlueprintSchemaBlueprintTypeReferenceAllOf
from core_client.model.blueprint_type_reference import BlueprintTypeReference
from core_client.model.blueprint_type_reference_kind import BlueprintTypeReferenceKind
from core_client.model.instance_schema_blueprint_type_reference import InstanceSchemaBlueprintTypeReference
from core_client.model.local_type_index import LocalTypeIndex
globals()['BlueprintSchemaBlueprintTypeReference'] = BlueprintSchemaBlueprintTypeReference
globals()['BlueprintSchemaBlueprintTypeReferenceAllOf'] = BlueprintSchemaBlueprintTypeReferenceAllOf
globals()['BlueprintTypeReference'] = BlueprintTypeReference
globals()['BlueprintTypeReferenceKind'] = BlueprintTypeReferenceKind
globals()['InstanceSchemaBlueprintTypeReference'] = InstanceSchemaBlueprintTypeReference
globals()['LocalTypeIndex'] = LocalTypeIndex
from core_client.model.blueprint_schema_blueprint_type_reference import BlueprintSchemaBlueprintTypeReference


class TestBlueprintSchemaBlueprintTypeReference(unittest.TestCase):
    """BlueprintSchemaBlueprintTypeReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintSchemaBlueprintTypeReference(self):
        """Test BlueprintSchemaBlueprintTypeReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintSchemaBlueprintTypeReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
