"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.state_consensus_manager_request import StateConsensusManagerRequest


class TestStateConsensusManagerRequest(unittest.TestCase):
    """StateConsensusManagerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateConsensusManagerRequest(self):
        """Test StateConsensusManagerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateConsensusManagerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
