"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule_node_type import AccessRuleNodeType


class TestAccessRuleNodeType(unittest.TestCase):
    """AccessRuleNodeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRuleNodeType(self):
        """Test AccessRuleNodeType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRuleNodeType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
