"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fungible_resource_amount_all_of import FungibleResourceAmountAllOf


class TestFungibleResourceAmountAllOf(unittest.TestCase):
    """FungibleResourceAmountAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFungibleResourceAmountAllOf(self):
        """Test FungibleResourceAmountAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FungibleResourceAmountAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
