"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.network_configuration_response_well_known_addresses import NetworkConfigurationResponseWellKnownAddresses


class TestNetworkConfigurationResponseWellKnownAddresses(unittest.TestCase):
    """NetworkConfigurationResponseWellKnownAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkConfigurationResponseWellKnownAddresses(self):
        """Test NetworkConfigurationResponseWellKnownAddresses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkConfigurationResponseWellKnownAddresses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
