"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_transaction_submit_priority_threshold_not_met_error_details_all_of import LtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf


class TestLtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf(unittest.TestCase):
    """LtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf(self):
        """Test LtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitPriorityThresholdNotMetErrorDetailsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
