"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.lts_committed_transaction_status import LtsCommittedTransactionStatus
from core_client.model.lts_entity_fungible_balance_changes import LtsEntityFungibleBalanceChanges
from core_client.model.lts_resultant_account_fungible_balances import LtsResultantAccountFungibleBalances
from core_client.model.state_version import StateVersion
from core_client.model.transaction_identifiers import TransactionIdentifiers
globals()['LtsCommittedTransactionStatus'] = LtsCommittedTransactionStatus
globals()['LtsEntityFungibleBalanceChanges'] = LtsEntityFungibleBalanceChanges
globals()['LtsResultantAccountFungibleBalances'] = LtsResultantAccountFungibleBalances
globals()['StateVersion'] = StateVersion
globals()['TransactionIdentifiers'] = TransactionIdentifiers
from core_client.model.lts_committed_transaction_outcome import LtsCommittedTransactionOutcome


class TestLtsCommittedTransactionOutcome(unittest.TestCase):
    """LtsCommittedTransactionOutcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsCommittedTransactionOutcome(self):
        """Test LtsCommittedTransactionOutcome"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsCommittedTransactionOutcome()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
