"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.multi_resource_pool_field_state_value import MultiResourcePoolFieldStateValue
globals()['MultiResourcePoolFieldStateValue'] = MultiResourcePoolFieldStateValue
from core_client.model.multi_resource_pool_field_state_substate_all_of import MultiResourcePoolFieldStateSubstateAllOf


class TestMultiResourcePoolFieldStateSubstateAllOf(unittest.TestCase):
    """MultiResourcePoolFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiResourcePoolFieldStateSubstateAllOf(self):
        """Test MultiResourcePoolFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiResourcePoolFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
