"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.code_hash import CodeHash


class TestCodeHash(unittest.TestCase):
    """CodeHash unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodeHash(self):
        """Test CodeHash"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CodeHash()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
