"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.package_code_instrumented_code_entry_value import PackageCodeInstrumentedCodeEntryValue
from core_client.model.package_code_key import PackageCodeKey
globals()['PackageCodeInstrumentedCodeEntryValue'] = PackageCodeInstrumentedCodeEntryValue
globals()['PackageCodeKey'] = PackageCodeKey
from core_client.model.package_code_instrumented_code_entry_substate_all_of import PackageCodeInstrumentedCodeEntrySubstateAllOf


class TestPackageCodeInstrumentedCodeEntrySubstateAllOf(unittest.TestCase):
    """PackageCodeInstrumentedCodeEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageCodeInstrumentedCodeEntrySubstateAllOf(self):
        """Test PackageCodeInstrumentedCodeEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageCodeInstrumentedCodeEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
