"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.committed_transaction import CommittedTransaction
from core_client.model.state_version import StateVersion
globals()['CommittedTransaction'] = CommittedTransaction
globals()['StateVersion'] = StateVersion
from core_client.model.stream_transactions_response import StreamTransactionsResponse


class TestStreamTransactionsResponse(unittest.TestCase):
    """StreamTransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamTransactionsResponse(self):
        """Test StreamTransactionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreamTransactionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
