"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.authorized_depositor_badge import AuthorizedDepositorBadge
globals()['AuthorizedDepositorBadge'] = AuthorizedDepositorBadge
from core_client.model.authorized_depositor_key import AuthorizedDepositorKey


class TestAuthorizedDepositorKey(unittest.TestCase):
    """AuthorizedDepositorKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorizedDepositorKey(self):
        """Test AuthorizedDepositorKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthorizedDepositorKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
