"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_version_key import BlueprintVersionKey
from core_client.model.package_blueprint_dependencies_entry_value import PackageBlueprintDependenciesEntryValue
globals()['BlueprintVersionKey'] = BlueprintVersionKey
globals()['PackageBlueprintDependenciesEntryValue'] = PackageBlueprintDependenciesEntryValue
from core_client.model.package_blueprint_dependencies_entry_substate_all_of import PackageBlueprintDependenciesEntrySubstateAllOf


class TestPackageBlueprintDependenciesEntrySubstateAllOf(unittest.TestCase):
    """PackageBlueprintDependenciesEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageBlueprintDependenciesEntrySubstateAllOf(self):
        """Test PackageBlueprintDependenciesEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageBlueprintDependenciesEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
