"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.object_hook import ObjectHook


class TestObjectHook(unittest.TestCase):
    """ObjectHook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectHook(self):
        """Test ObjectHook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectHook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
