"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.account_vault_entry_value import AccountVaultEntryValue
from core_client.model.resource_key import ResourceKey
globals()['AccountVaultEntryValue'] = AccountVaultEntryValue
globals()['ResourceKey'] = ResourceKey
from core_client.model.account_vault_entry_substate_all_of import AccountVaultEntrySubstateAllOf


class TestAccountVaultEntrySubstateAllOf(unittest.TestCase):
    """AccountVaultEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountVaultEntrySubstateAllOf(self):
        """Test AccountVaultEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountVaultEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
