"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fully_scoped_type_id import FullyScopedTypeId
globals()['FullyScopedTypeId'] = FullyScopedTypeId
from core_client.model.package_type_reference import PackageTypeReference


class TestPackageTypeReference(unittest.TestCase):
    """PackageTypeReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageTypeReference(self):
        """Test PackageTypeReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageTypeReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
