"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.blueprint_collection_schema import BlueprintCollectionSchema
globals()['BlueprintCollectionSchema'] = BlueprintCollectionSchema
from core_client.model.blueprint_schema_collection_partition import BlueprintSchemaCollectionPartition


class TestBlueprintSchemaCollectionPartition(unittest.TestCase):
    """BlueprintSchemaCollectionPartition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintSchemaCollectionPartition(self):
        """Test BlueprintSchemaCollectionPartition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintSchemaCollectionPartition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
