"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.consensus_manager_field_config_value import ConsensusManagerFieldConfigValue
globals()['ConsensusManagerFieldConfigValue'] = ConsensusManagerFieldConfigValue
from core_client.model.consensus_manager_field_config_substate_all_of import ConsensusManagerFieldConfigSubstateAllOf


class TestConsensusManagerFieldConfigSubstateAllOf(unittest.TestCase):
    """ConsensusManagerFieldConfigSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldConfigSubstateAllOf(self):
        """Test ConsensusManagerFieldConfigSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldConfigSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
