"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.committed_intent_metadata import CommittedIntentMetadata
globals()['CommittedIntentMetadata'] = CommittedIntentMetadata
from core_client.model.lts_transaction_submit_intent_already_committed_all_of import LtsTransactionSubmitIntentAlreadyCommittedAllOf


class TestLtsTransactionSubmitIntentAlreadyCommittedAllOf(unittest.TestCase):
    """LtsTransactionSubmitIntentAlreadyCommittedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitIntentAlreadyCommittedAllOf(self):
        """Test LtsTransactionSubmitIntentAlreadyCommittedAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitIntentAlreadyCommittedAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
