"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.main_method_key import MainMethodKey


class TestMainMethodKey(unittest.TestCase):
    """MainMethodKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMainMethodKey(self):
        """Test MainMethodKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MainMethodKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
