"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fungible_resource_amount import FungibleResourceAmount
from core_client.model.non_fungible_local_id import NonFungibleLocalId
from core_client.model.non_fungible_resource_amount import NonFungibleResourceAmount
from core_client.model.non_fungible_resource_amount_all_of import NonFungibleResourceAmountAllOf
from core_client.model.resource_amount import ResourceAmount
from core_client.model.resource_type import ResourceType
globals()['FungibleResourceAmount'] = FungibleResourceAmount
globals()['NonFungibleLocalId'] = NonFungibleLocalId
globals()['NonFungibleResourceAmount'] = NonFungibleResourceAmount
globals()['NonFungibleResourceAmountAllOf'] = NonFungibleResourceAmountAllOf
globals()['ResourceAmount'] = ResourceAmount
globals()['ResourceType'] = ResourceType
from core_client.model.non_fungible_resource_amount import NonFungibleResourceAmount


class TestNonFungibleResourceAmount(unittest.TestCase):
    """NonFungibleResourceAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleResourceAmount(self):
        """Test NonFungibleResourceAmount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleResourceAmount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
