"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.account_vault_index_entry_value import AccountVaultIndexEntryValue
from core_client.model.resource_key import ResourceKey
globals()['AccountVaultIndexEntryValue'] = AccountVaultIndexEntryValue
globals()['ResourceKey'] = ResourceKey
from core_client.model.account_vault_index_entry_substate_all_of import AccountVaultIndexEntrySubstateAllOf


class TestAccountVaultIndexEntrySubstateAllOf(unittest.TestCase):
    """AccountVaultIndexEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountVaultIndexEntrySubstateAllOf(self):
        """Test AccountVaultIndexEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountVaultIndexEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
