"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.parsed_notarized_transaction_all_of_validation_error import ParsedNotarizedTransactionAllOfValidationError


class TestParsedNotarizedTransactionAllOfValidationError(unittest.TestCase):
    """ParsedNotarizedTransactionAllOfValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParsedNotarizedTransactionAllOfValidationError(self):
        """Test ParsedNotarizedTransactionAllOfValidationError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParsedNotarizedTransactionAllOfValidationError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
