"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.account_field_state_value import AccountFieldStateValue
globals()['AccountFieldStateValue'] = AccountFieldStateValue
from core_client.model.account_field_state_substate_all_of import AccountFieldStateSubstateAllOf


class TestAccountFieldStateSubstateAllOf(unittest.TestCase):
    """AccountFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountFieldStateSubstateAllOf(self):
        """Test AccountFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
