"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.royalty_payment import RoyaltyPayment
from core_client.model.vault_payment import VaultPayment
globals()['RoyaltyPayment'] = RoyaltyPayment
globals()['VaultPayment'] = VaultPayment
from core_client.model.fee_summary import FeeSummary


class TestFeeSummary(unittest.TestCase):
    """FeeSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeeSummary(self):
        """Test FeeSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FeeSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
