"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.owner_role_updater import OwnerRoleUpdater


class TestOwnerRoleUpdater(unittest.TestCase):
    """OwnerRoleUpdater unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnerRoleUpdater(self):
        """Test OwnerRoleUpdater"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwnerRoleUpdater()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
