"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_format_options import SborFormatOptions
from core_client.model.state_version import StateVersion
from core_client.model.substate_format_options import SubstateFormatOptions
from core_client.model.transaction_format_options import TransactionFormatOptions
globals()['SborFormatOptions'] = SborFormatOptions
globals()['StateVersion'] = StateVersion
globals()['SubstateFormatOptions'] = SubstateFormatOptions
globals()['TransactionFormatOptions'] = TransactionFormatOptions
from core_client.model.stream_transactions_request import StreamTransactionsRequest


class TestStreamTransactionsRequest(unittest.TestCase):
    """StreamTransactionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamTransactionsRequest(self):
        """Test StreamTransactionsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreamTransactionsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
