"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.notarized_transaction_hash import NotarizedTransactionHash
from core_client.model.state_version import StateVersion
globals()['NotarizedTransactionHash'] = NotarizedTransactionHash
globals()['StateVersion'] = StateVersion
from core_client.model.committed_intent_metadata import CommittedIntentMetadata


class TestCommittedIntentMetadata(unittest.TestCase):
    """CommittedIntentMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommittedIntentMetadata(self):
        """Test CommittedIntentMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommittedIntentMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
