"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_data import SborData
globals()['SborData'] = SborData
from core_client.model.scrypto_schema import ScryptoSchema


class TestScryptoSchema(unittest.TestCase):
    """ScryptoSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScryptoSchema(self):
        """Test ScryptoSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScryptoSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
