"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.map_substate_key_all_of import MapSubstateKeyAllOf


class TestMapSubstateKeyAllOf(unittest.TestCase):
    """MapSubstateKeyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapSubstateKeyAllOf(self):
        """Test MapSubstateKeyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MapSubstateKeyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
