"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.package_field_royalty_accumulator_value import PackageFieldRoyaltyAccumulatorValue
globals()['PackageFieldRoyaltyAccumulatorValue'] = PackageFieldRoyaltyAccumulatorValue
from core_client.model.package_field_royalty_accumulator_substate_all_of import PackageFieldRoyaltyAccumulatorSubstateAllOf


class TestPackageFieldRoyaltyAccumulatorSubstateAllOf(unittest.TestCase):
    """PackageFieldRoyaltyAccumulatorSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageFieldRoyaltyAccumulatorSubstateAllOf(self):
        """Test PackageFieldRoyaltyAccumulatorSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageFieldRoyaltyAccumulatorSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
