"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.fungible_vault_field_balance_value import FungibleVaultFieldBalanceValue
globals()['FungibleVaultFieldBalanceValue'] = FungibleVaultFieldBalanceValue
from core_client.model.fungible_vault_field_balance_substate_all_of import FungibleVaultFieldBalanceSubstateAllOf


class TestFungibleVaultFieldBalanceSubstateAllOf(unittest.TestCase):
    """FungibleVaultFieldBalanceSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFungibleVaultFieldBalanceSubstateAllOf(self):
        """Test FungibleVaultFieldBalanceSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FungibleVaultFieldBalanceSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
