"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.sbor_data import SborData


class TestSborData(unittest.TestCase):
    """SborData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSborData(self):
        """Test SborData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SborData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
