"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.consensus_manager_field_current_proposal_statistic_value import ConsensusManagerFieldCurrentProposalStatisticValue
globals()['ConsensusManagerFieldCurrentProposalStatisticValue'] = ConsensusManagerFieldCurrentProposalStatisticValue
from core_client.model.consensus_manager_field_current_proposal_statistic_substate_all_of import ConsensusManagerFieldCurrentProposalStatisticSubstateAllOf


class TestConsensusManagerFieldCurrentProposalStatisticSubstateAllOf(unittest.TestCase):
    """ConsensusManagerFieldCurrentProposalStatisticSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldCurrentProposalStatisticSubstateAllOf(self):
        """Test ConsensusManagerFieldCurrentProposalStatisticSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldCurrentProposalStatisticSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
