"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rule import AccessRule
globals()['AccessRule'] = AccessRule
from core_client.model.recovery_proposal import RecoveryProposal


class TestRecoveryProposal(unittest.TestCase):
    """RecoveryProposal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoveryProposal(self):
        """Test RecoveryProposal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoveryProposal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
