"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.royalty_module_field_state_value import RoyaltyModuleFieldStateValue
globals()['RoyaltyModuleFieldStateValue'] = RoyaltyModuleFieldStateValue
from core_client.model.royalty_module_field_state_substate_all_of import RoyaltyModuleFieldStateSubstateAllOf


class TestRoyaltyModuleFieldStateSubstateAllOf(unittest.TestCase):
    """RoyaltyModuleFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoyaltyModuleFieldStateSubstateAllOf(self):
        """Test RoyaltyModuleFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoyaltyModuleFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
