"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.basic_error_response import BasicErrorResponse
from core_client.model.error_response import ErrorResponse
from core_client.model.error_response_type import ErrorResponseType
from core_client.model.lts_transaction_submit_error_details import LtsTransactionSubmitErrorDetails
from core_client.model.lts_transaction_submit_error_response import LtsTransactionSubmitErrorResponse
from core_client.model.lts_transaction_submit_error_response_all_of import LtsTransactionSubmitErrorResponseAllOf
from core_client.model.transaction_submit_error_response import TransactionSubmitErrorResponse
globals()['BasicErrorResponse'] = BasicErrorResponse
globals()['ErrorResponse'] = ErrorResponse
globals()['ErrorResponseType'] = ErrorResponseType
globals()['LtsTransactionSubmitErrorDetails'] = LtsTransactionSubmitErrorDetails
globals()['LtsTransactionSubmitErrorResponse'] = LtsTransactionSubmitErrorResponse
globals()['LtsTransactionSubmitErrorResponseAllOf'] = LtsTransactionSubmitErrorResponseAllOf
globals()['TransactionSubmitErrorResponse'] = TransactionSubmitErrorResponse
from core_client.model.lts_transaction_submit_error_response import LtsTransactionSubmitErrorResponse


class TestLtsTransactionSubmitErrorResponse(unittest.TestCase):
    """LtsTransactionSubmitErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitErrorResponse(self):
        """Test LtsTransactionSubmitErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
