"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.instant import Instant
from core_client.model.lts_transaction_submit_error_details import LtsTransactionSubmitErrorDetails
from core_client.model.lts_transaction_submit_error_details_type import LtsTransactionSubmitErrorDetailsType
from core_client.model.lts_transaction_submit_priority_threshold_not_met_error_details import LtsTransactionSubmitPriorityThresholdNotMetErrorDetails
from core_client.model.lts_transaction_submit_rejected_error_details import LtsTransactionSubmitRejectedErrorDetails
from core_client.model.lts_transaction_submit_rejected_error_details_all_of import LtsTransactionSubmitRejectedErrorDetailsAllOf
globals()['Instant'] = Instant
globals()['LtsTransactionSubmitErrorDetails'] = LtsTransactionSubmitErrorDetails
globals()['LtsTransactionSubmitErrorDetailsType'] = LtsTransactionSubmitErrorDetailsType
globals()['LtsTransactionSubmitPriorityThresholdNotMetErrorDetails'] = LtsTransactionSubmitPriorityThresholdNotMetErrorDetails
globals()['LtsTransactionSubmitRejectedErrorDetails'] = LtsTransactionSubmitRejectedErrorDetails
globals()['LtsTransactionSubmitRejectedErrorDetailsAllOf'] = LtsTransactionSubmitRejectedErrorDetailsAllOf
from core_client.model.lts_transaction_submit_rejected_error_details import LtsTransactionSubmitRejectedErrorDetails


class TestLtsTransactionSubmitRejectedErrorDetails(unittest.TestCase):
    """LtsTransactionSubmitRejectedErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLtsTransactionSubmitRejectedErrorDetails(self):
        """Test LtsTransactionSubmitRejectedErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LtsTransactionSubmitRejectedErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
