"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.auth_config import AuthConfig
globals()['AuthConfig'] = AuthConfig
from core_client.model.package_blueprint_auth_template_entry_value import PackageBlueprintAuthTemplateEntryValue


class TestPackageBlueprintAuthTemplateEntryValue(unittest.TestCase):
    """PackageBlueprintAuthTemplateEntryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageBlueprintAuthTemplateEntryValue(self):
        """Test PackageBlueprintAuthTemplateEntryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PackageBlueprintAuthTemplateEntryValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
