"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.consensus_manager_field_current_validator_set_value import ConsensusManagerFieldCurrentValidatorSetValue
globals()['ConsensusManagerFieldCurrentValidatorSetValue'] = ConsensusManagerFieldCurrentValidatorSetValue
from core_client.model.consensus_manager_field_current_validator_set_substate_all_of import ConsensusManagerFieldCurrentValidatorSetSubstateAllOf


class TestConsensusManagerFieldCurrentValidatorSetSubstateAllOf(unittest.TestCase):
    """ConsensusManagerFieldCurrentValidatorSetSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldCurrentValidatorSetSubstateAllOf(self):
        """Test ConsensusManagerFieldCurrentValidatorSetSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldCurrentValidatorSetSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
