"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.generic_scrypto_component_field_state_value import GenericScryptoComponentFieldStateValue
globals()['GenericScryptoComponentFieldStateValue'] = GenericScryptoComponentFieldStateValue
from core_client.model.generic_scrypto_component_field_state_substate_all_of import GenericScryptoComponentFieldStateSubstateAllOf


class TestGenericScryptoComponentFieldStateSubstateAllOf(unittest.TestCase):
    """GenericScryptoComponentFieldStateSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericScryptoComponentFieldStateSubstateAllOf(self):
        """Test GenericScryptoComponentFieldStateSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericScryptoComponentFieldStateSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
