"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.non_fungible_vault_field_frozen_status_value import NonFungibleVaultFieldFrozenStatusValue
globals()['NonFungibleVaultFieldFrozenStatusValue'] = NonFungibleVaultFieldFrozenStatusValue
from core_client.model.non_fungible_vault_field_frozen_status_substate_all_of import NonFungibleVaultFieldFrozenStatusSubstateAllOf


class TestNonFungibleVaultFieldFrozenStatusSubstateAllOf(unittest.TestCase):
    """NonFungibleVaultFieldFrozenStatusSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNonFungibleVaultFieldFrozenStatusSubstateAllOf(self):
        """Test NonFungibleVaultFieldFrozenStatusSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NonFungibleVaultFieldFrozenStatusSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
