"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.authorized_depositor_badge_type import AuthorizedDepositorBadgeType
from core_client.model.non_fungible_authorized_depositor_badge import NonFungibleAuthorizedDepositorBadge
from core_client.model.resource_authorized_depositor_badge import ResourceAuthorizedDepositorBadge
globals()['AuthorizedDepositorBadgeType'] = AuthorizedDepositorBadgeType
globals()['NonFungibleAuthorizedDepositorBadge'] = NonFungibleAuthorizedDepositorBadge
globals()['ResourceAuthorizedDepositorBadge'] = ResourceAuthorizedDepositorBadge
from core_client.model.authorized_depositor_badge import AuthorizedDepositorBadge


class TestAuthorizedDepositorBadge(unittest.TestCase):
    """AuthorizedDepositorBadge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorizedDepositorBadge(self):
        """Test AuthorizedDepositorBadge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthorizedDepositorBadge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
