"""
    Radix Core API - Babylon

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.generic_substitution import GenericSubstitution
globals()['GenericSubstitution'] = GenericSubstitution
from core_client.model.blueprint_info import BlueprintInfo


class TestBlueprintInfo(unittest.TestCase):
    """BlueprintInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlueprintInfo(self):
        """Test BlueprintInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlueprintInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
