"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.entity_reference import EntityReference
globals()['EntityReference'] = EntityReference
from core_client.model.royalty_module_field_state_value import RoyaltyModuleFieldStateValue


class TestRoyaltyModuleFieldStateValue(unittest.TestCase):
    """RoyaltyModuleFieldStateValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoyaltyModuleFieldStateValue(self):
        """Test RoyaltyModuleFieldStateValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoyaltyModuleFieldStateValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
