"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.type_pointer_type import TypePointerType


class TestTypePointerType(unittest.TestCase):
    """TypePointerType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypePointerType(self):
        """Test TypePointerType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypePointerType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
