"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.access_rules_module_rule_entry_value import AccessRulesModuleRuleEntryValue
from core_client.model.object_role_key import ObjectRoleKey
globals()['AccessRulesModuleRuleEntryValue'] = AccessRulesModuleRuleEntryValue
globals()['ObjectRoleKey'] = ObjectRoleKey
from core_client.model.access_rules_module_rule_entry_substate_all_of import AccessRulesModuleRuleEntrySubstateAllOf


class TestAccessRulesModuleRuleEntrySubstateAllOf(unittest.TestCase):
    """AccessRulesModuleRuleEntrySubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessRulesModuleRuleEntrySubstateAllOf(self):
        """Test AccessRulesModuleRuleEntrySubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessRulesModuleRuleEntrySubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
