"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.consensus_manager_field_validator_rewards_value import ConsensusManagerFieldValidatorRewardsValue
globals()['ConsensusManagerFieldValidatorRewardsValue'] = ConsensusManagerFieldValidatorRewardsValue
from core_client.model.consensus_manager_field_validator_rewards_substate_all_of import ConsensusManagerFieldValidatorRewardsSubstateAllOf


class TestConsensusManagerFieldValidatorRewardsSubstateAllOf(unittest.TestCase):
    """ConsensusManagerFieldValidatorRewardsSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsensusManagerFieldValidatorRewardsSubstateAllOf(self):
        """Test ConsensusManagerFieldValidatorRewardsSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConsensusManagerFieldValidatorRewardsSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
