"""
    Babylon Core API - RCnet V2

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import sys
import unittest

import core_client
from core_client.model.validator_field_protocol_update_readiness_signal_value import ValidatorFieldProtocolUpdateReadinessSignalValue
globals()['ValidatorFieldProtocolUpdateReadinessSignalValue'] = ValidatorFieldProtocolUpdateReadinessSignalValue
from core_client.model.validator_field_protocol_update_readiness_signal_substate_all_of import ValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf


class TestValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf(unittest.TestCase):
    """ValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf(self):
        """Test ValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValidatorFieldProtocolUpdateReadinessSignalSubstateAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
