"""
    Radix Core API

    Generated by https://openapi-generator.tech with customisation from https://github.com/radixdlt/python-core-client/
"""


import re  # noqa: F401
import sys  # noqa: F401

from core_client.api_client import ApiClient, Endpoint as _Endpoint
from core_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from core_client.model.mempool_request import MempoolRequest
from core_client.model.mempool_response import MempoolResponse
from core_client.model.mempool_transaction_request import MempoolTransactionRequest
from core_client.model.mempool_transaction_response import MempoolTransactionResponse
from core_client.model.unexpected_error import UnexpectedError


class MempoolApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __mempool_post(
            self,
            mempool_request,
            **kwargs
        ):
            """Get Mempool Transactions  # noqa: E501

            Gets the transaction identifiers in the mempool  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.mempool_post(mempool_request, async_req=True)
            >>> result = thread.get()

            Args:
                mempool_request (MempoolRequest):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                MempoolResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['mempool_request'] = \
                mempool_request
            return self.call_with_http_info(**kwargs)

        self.mempool_post = _Endpoint(
            settings={
                'response_type': (MempoolResponse,),
                'auth': [],
                'endpoint_path': '/mempool',
                'operation_id': 'mempool_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'mempool_request',
                ],
                'required': [
                    'mempool_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'mempool_request':
                        (MempoolRequest,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'mempool_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__mempool_post
        )

        def __mempool_transaction_post(
            self,
            mempool_transaction_request,
            **kwargs
        ):
            """Get Mempool Transaction  # noqa: E501

            Gets the transaction from the mempool  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.mempool_transaction_post(mempool_transaction_request, async_req=True)
            >>> result = thread.get()

            Args:
                mempool_transaction_request (MempoolTransactionRequest):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                MempoolTransactionResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['mempool_transaction_request'] = \
                mempool_transaction_request
            return self.call_with_http_info(**kwargs)

        self.mempool_transaction_post = _Endpoint(
            settings={
                'response_type': (MempoolTransactionResponse,),
                'auth': [],
                'endpoint_path': '/mempool/transaction',
                'operation_id': 'mempool_transaction_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'mempool_transaction_request',
                ],
                'required': [
                    'mempool_transaction_request',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'mempool_transaction_request':
                        (MempoolTransactionRequest,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'mempool_transaction_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__mempool_transaction_post
        )
